// Code generated by protoc-gen-go.
// source: events.proto
// DO NOT EDIT!

/*
Package events is a generated protocol buffer package.

It is generated from these files:
	events.proto

It has these top-level messages:
	ProjectCreated
	DatasetCreated
	DatasetUpdated
	JobAdded
	ServiceCreated
	ServiceMetadata
	ExpertAdded
	DatasetSample
	DatasetMetadata
	Event
*/
package events

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type STATE int32

const (
	STATE_NONE   STATE = 0
	STATE_VALUE  STATE = 1
	STATE_DELETE STATE = 2
)

var STATE_name = map[int32]string{
	0: "NONE",
	1: "VALUE",
	2: "DELETE",
}
var STATE_value = map[string]int32{
	"NONE":   0,
	"VALUE":  1,
	"DELETE": 2,
}

func (x STATE) String() string {
	return proto.EnumName(STATE_name, int32(x))
}
func (STATE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Type int32

const (
	Type_None                 Type = 0
	Type_Event_ProjectCreated Type = 1
	Type_Event_DatasetCreated Type = 2
	Type_Event_DatasetUpdated Type = 3
	Type_Event_ExpertAdded    Type = 4
	Type_Event_JobAdded       Type = 5
	Type_Event_ServiceCreated Type = 6
)

var Type_name = map[int32]string{
	0: "None",
	1: "Event_ProjectCreated",
	2: "Event_DatasetCreated",
	3: "Event_DatasetUpdated",
	4: "Event_ExpertAdded",
	5: "Event_JobAdded",
	6: "Event_ServiceCreated",
}
var Type_value = map[string]int32{
	"None":                 0,
	"Event_ProjectCreated": 1,
	"Event_DatasetCreated": 2,
	"Event_DatasetUpdated": 3,
	"Event_ExpertAdded":    4,
	"Event_JobAdded":       5,
	"Event_ServiceCreated": 6,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Sample storage format. Doesn't necessarily match
// actual data format which could be very cryptic
type DatasetSample_FORMAT int32

const (
	DatasetSample_TEXT DatasetSample_FORMAT = 0
	DatasetSample_TSV  DatasetSample_FORMAT = 1
	DatasetSample_JSON DatasetSample_FORMAT = 2
)

var DatasetSample_FORMAT_name = map[int32]string{
	0: "TEXT",
	1: "TSV",
	2: "JSON",
}
var DatasetSample_FORMAT_value = map[string]int32{
	"TEXT": 0,
	"TSV":  1,
	"JSON": 2,
}

func (x DatasetSample_FORMAT) String() string {
	return proto.EnumName(DatasetSample_FORMAT_name, int32(x))
}
func (DatasetSample_FORMAT) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type ProjectCreated struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ProjectCreated) Reset()                    { *m = ProjectCreated{} }
func (m *ProjectCreated) String() string            { return proto.CompactTextString(m) }
func (*ProjectCreated) ProtoMessage()               {}
func (*ProjectCreated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DatasetCreated struct {
	DatasetId string           `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	ProjectId string           `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Name      string           `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Meta      *DatasetMetadata `protobuf:"bytes,4,opt,name=meta" json:"meta,omitempty"`
}

func (m *DatasetCreated) Reset()                    { *m = DatasetCreated{} }
func (m *DatasetCreated) String() string            { return proto.CompactTextString(m) }
func (*DatasetCreated) ProtoMessage()               {}
func (*DatasetCreated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DatasetCreated) GetMeta() *DatasetMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

type DatasetUpdated struct {
	DatasetId string           `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	ProjectId string           `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Meta      *DatasetMetadata `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
}

func (m *DatasetUpdated) Reset()                    { *m = DatasetUpdated{} }
func (m *DatasetUpdated) String() string            { return proto.CompactTextString(m) }
func (*DatasetUpdated) ProtoMessage()               {}
func (*DatasetUpdated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DatasetUpdated) GetMeta() *DatasetMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

type JobAdded struct {
	JobId     string   `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobName   string   `protobuf:"bytes,2,opt,name=job_name,json=jobName" json:"job_name,omitempty"`
	Inputs    []string `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty"`
	Outputs   []string `protobuf:"bytes,4,rep,name=outputs" json:"outputs,omitempty"`
	ProjectId string   `protobuf:"bytes,5,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *JobAdded) Reset()                    { *m = JobAdded{} }
func (m *JobAdded) String() string            { return proto.CompactTextString(m) }
func (*JobAdded) ProtoMessage()               {}
func (*JobAdded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ServiceCreated struct {
	ServiceId string           `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	ProjectId string           `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Meta      *ServiceMetadata `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
}

func (m *ServiceCreated) Reset()                    { *m = ServiceCreated{} }
func (m *ServiceCreated) String() string            { return proto.CompactTextString(m) }
func (*ServiceCreated) ProtoMessage()               {}
func (*ServiceCreated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServiceCreated) GetMeta() *ServiceMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ServiceMetadata struct {
	ServiceName    string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	ServiceNameSet bool     `protobuf:"varint,2,opt,name=service_name_set,json=serviceNameSet" json:"service_name_set,omitempty"`
	LocationId     string   `protobuf:"bytes,3,opt,name=location_id,json=locationId" json:"location_id,omitempty"`
	LocationIdSet  bool     `protobuf:"varint,4,opt,name=location_id_set,json=locationIdSet" json:"location_id_set,omitempty"`
	LocationUri    string   `protobuf:"bytes,5,opt,name=location_uri,json=locationUri" json:"location_uri,omitempty"`
	LocationUriSet bool     `protobuf:"varint,6,opt,name=location_uri_set,json=locationUriSet" json:"location_uri_set,omitempty"`
	Description    string   `protobuf:"bytes,7,opt,name=description" json:"description,omitempty"`
	DescriptionSet bool     `protobuf:"varint,8,opt,name=description_set,json=descriptionSet" json:"description_set,omitempty"`
	Experts        []string `protobuf:"bytes,9,rep,name=experts" json:"experts,omitempty"`
	ExpertsSet     bool     `protobuf:"varint,10,opt,name=experts_set,json=expertsSet" json:"experts_set,omitempty"`
}

func (m *ServiceMetadata) Reset()                    { *m = ServiceMetadata{} }
func (m *ServiceMetadata) String() string            { return proto.CompactTextString(m) }
func (*ServiceMetadata) ProtoMessage()               {}
func (*ServiceMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ExpertAdded struct {
	ExpertId   string `protobuf:"bytes,1,opt,name=expert_id,json=expertId" json:"expert_id,omitempty"`
	ExpertName string `protobuf:"bytes,2,opt,name=expert_name,json=expertName" json:"expert_name,omitempty"`
}

func (m *ExpertAdded) Reset()                    { *m = ExpertAdded{} }
func (m *ExpertAdded) String() string            { return proto.CompactTextString(m) }
func (*ExpertAdded) ProtoMessage()               {}
func (*ExpertAdded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DatasetSample struct {
	Format DatasetSample_FORMAT `protobuf:"varint,1,opt,name=format,enum=DatasetSample_FORMAT" json:"format,omitempty"`
	Body   []byte               `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *DatasetSample) Reset()                    { *m = DatasetSample{} }
func (m *DatasetSample) String() string            { return proto.CompactTextString(m) }
func (*DatasetSample) ProtoMessage()               {}
func (*DatasetSample) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// if a field kind is set, then the corresponding property carries
// a new value (which could be null)
type DatasetMetadata struct {
	RecordCount        int64          `protobuf:"varint,1,opt,name=record_count,json=recordCount" json:"record_count,omitempty"`
	RecordCountSet     bool           `protobuf:"varint,2,opt,name=record_count_set,json=recordCountSet" json:"record_count_set,omitempty"`
	FileCount          int64          `protobuf:"varint,3,opt,name=file_count,json=fileCount" json:"file_count,omitempty"`
	FileCountSet       bool           `protobuf:"varint,4,opt,name=file_count_set,json=fileCountSet" json:"file_count_set,omitempty"`
	StorageBytes       int64          `protobuf:"varint,5,opt,name=storage_bytes,json=storageBytes" json:"storage_bytes,omitempty"`
	StorageBytesSet    bool           `protobuf:"varint,6,opt,name=storage_bytes_set,json=storageBytesSet" json:"storage_bytes_set,omitempty"`
	Sample             *DatasetSample `protobuf:"bytes,7,opt,name=sample" json:"sample,omitempty"`
	SampleSet          bool           `protobuf:"varint,8,opt,name=sample_set,json=sampleSet" json:"sample_set,omitempty"`
	UpdateTimestamp    int64          `protobuf:"varint,9,opt,name=update_timestamp,json=updateTimestamp" json:"update_timestamp,omitempty"`
	UpdateTimestampSet bool           `protobuf:"varint,10,opt,name=update_timestamp_set,json=updateTimestampSet" json:"update_timestamp_set,omitempty"`
	DataFormat         string         `protobuf:"bytes,11,opt,name=data_format,json=dataFormat" json:"data_format,omitempty"`
	DataFormatSet      bool           `protobuf:"varint,12,opt,name=data_format_set,json=dataFormatSet" json:"data_format_set,omitempty"`
	Description        string         `protobuf:"bytes,13,opt,name=description" json:"description,omitempty"`
	DescriptionSet     bool           `protobuf:"varint,14,opt,name=description_set,json=descriptionSet" json:"description_set,omitempty"`
	LocationId         string         `protobuf:"bytes,15,opt,name=location_id,json=locationId" json:"location_id,omitempty"`
	LocationIdSet      bool           `protobuf:"varint,16,opt,name=location_id_set,json=locationIdSet" json:"location_id_set,omitempty"`
	LocationUri        string         `protobuf:"bytes,17,opt,name=location_uri,json=locationUri" json:"location_uri,omitempty"`
	LocationUriSet     bool           `protobuf:"varint,18,opt,name=location_uri_set,json=locationUriSet" json:"location_uri_set,omitempty"`
	Experts            []string       `protobuf:"bytes,19,rep,name=experts" json:"experts,omitempty"`
	ExpertsSet         bool           `protobuf:"varint,20,opt,name=experts_set,json=expertsSet" json:"experts_set,omitempty"`
}

func (m *DatasetMetadata) Reset()                    { *m = DatasetMetadata{} }
func (m *DatasetMetadata) String() string            { return proto.CompactTextString(m) }
func (*DatasetMetadata) ProtoMessage()               {}
func (*DatasetMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DatasetMetadata) GetSample() *DatasetSample {
	if m != nil {
		return m.Sample
	}
	return nil
}

type Event struct {
	Body []byte `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	Type Type   `protobuf:"varint,2,opt,name=Type,enum=Type" json:"Type,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*ProjectCreated)(nil), "ProjectCreated")
	proto.RegisterType((*DatasetCreated)(nil), "DatasetCreated")
	proto.RegisterType((*DatasetUpdated)(nil), "DatasetUpdated")
	proto.RegisterType((*JobAdded)(nil), "JobAdded")
	proto.RegisterType((*ServiceCreated)(nil), "ServiceCreated")
	proto.RegisterType((*ServiceMetadata)(nil), "ServiceMetadata")
	proto.RegisterType((*ExpertAdded)(nil), "ExpertAdded")
	proto.RegisterType((*DatasetSample)(nil), "DatasetSample")
	proto.RegisterType((*DatasetMetadata)(nil), "DatasetMetadata")
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterEnum("STATE", STATE_name, STATE_value)
	proto.RegisterEnum("Type", Type_name, Type_value)
	proto.RegisterEnum("DatasetSample_FORMAT", DatasetSample_FORMAT_name, DatasetSample_FORMAT_value)
}

func init() { proto.RegisterFile("events.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 877 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0x51, 0x6f, 0xdb, 0x36,
	0x10, 0x8e, 0x2c, 0x5b, 0xb6, 0xce, 0x8e, 0xc4, 0x70, 0xc9, 0xa0, 0x6e, 0x28, 0x9a, 0x7a, 0x5d,
	0xe6, 0x05, 0x98, 0x3b, 0x64, 0xc0, 0xde, 0xd3, 0x54, 0x05, 0xdc, 0xb5, 0xc9, 0x20, 0x2b, 0xc5,
	0xde, 0x0c, 0xc9, 0x62, 0x02, 0x05, 0xb1, 0x29, 0x48, 0x74, 0xb1, 0xfc, 0x83, 0xbd, 0xec, 0x57,
	0xec, 0x5f, 0x0e, 0x18, 0x30, 0xf0, 0x48, 0x5b, 0xb4, 0x9a, 0x05, 0x19, 0xd0, 0x37, 0xf2, 0xbb,
	0xcf, 0xdf, 0x9d, 0x8e, 0xf7, 0x91, 0x86, 0x01, 0xfb, 0xc8, 0x96, 0xa2, 0x1a, 0x17, 0x25, 0x17,
	0xfc, 0xab, 0x67, 0xd7, 0x9c, 0x5f, 0xdf, 0xb2, 0x97, 0xb8, 0x4b, 0x57, 0x57, 0x2f, 0x45, 0xbe,
	0x60, 0x95, 0x48, 0x16, 0x85, 0x22, 0x0c, 0xcf, 0xc0, 0xfb, 0xb5, 0xe4, 0x37, 0x6c, 0x2e, 0xce,
	0x4a, 0x96, 0x08, 0x96, 0xd1, 0xa7, 0x00, 0x85, 0x42, 0x66, 0x79, 0x16, 0x58, 0x87, 0xd6, 0xc8,
	0x8d, 0x5c, 0x8d, 0x4c, 0x32, 0x4a, 0xa1, 0xbd, 0x4c, 0x16, 0x2c, 0x68, 0x61, 0x00, 0xd7, 0xc3,
	0x3f, 0x2c, 0xf0, 0x5e, 0x27, 0x22, 0xa9, 0x98, 0xa9, 0x92, 0x29, 0xc4, 0x50, 0xd1, 0xc8, 0xa4,
	0x99, 0xa4, 0xf5, 0x5f, 0x49, 0xec, 0x3a, 0x09, 0x7d, 0x01, 0xed, 0x05, 0x13, 0x49, 0xd0, 0x3e,
	0xb4, 0x46, 0xfd, 0x13, 0x32, 0xd6, 0x09, 0xdf, 0x33, 0x91, 0x48, 0xdd, 0x08, 0xa3, 0x43, 0xb1,
	0xa9, 0xe4, 0xb2, 0xc8, 0x3e, 0x43, 0x25, 0xeb, 0xac, 0xf6, 0x83, 0x59, 0xff, 0xb4, 0xa0, 0xf7,
	0x96, 0xa7, 0xa7, 0x59, 0xc6, 0x32, 0x7a, 0x00, 0xce, 0x0d, 0x4f, 0xeb, 0x64, 0x9d, 0x1b, 0x9e,
	0x4e, 0x32, 0xfa, 0x04, 0x7a, 0x12, 0x36, 0x9a, 0xd7, 0xbd, 0xe1, 0xe9, 0xb9, 0xfc, 0xb4, 0x2f,
	0xc1, 0xc9, 0x97, 0xc5, 0x4a, 0x54, 0x81, 0x7d, 0x68, 0x8f, 0xdc, 0x48, 0xef, 0x68, 0x00, 0x5d,
	0xbe, 0x12, 0x18, 0x68, 0x63, 0x60, 0xbd, 0x6d, 0x54, 0xdd, 0x69, 0x54, 0x2d, 0xbb, 0x30, 0x65,
	0xe5, 0xc7, 0x7c, 0xce, 0x8c, 0xf3, 0xa8, 0x14, 0x62, 0x74, 0x41, 0x23, 0xff, 0xbf, 0x0b, 0x5a,
	0xbc, 0xd1, 0x85, 0xbf, 0x5b, 0xe0, 0x37, 0x22, 0xf4, 0x39, 0x0c, 0xd6, 0x79, 0xf1, 0xcb, 0x55,
	0xe6, 0xbe, 0xc6, 0xf0, 0xeb, 0x47, 0x40, 0x4c, 0xca, 0xac, 0x62, 0x02, 0x2b, 0xe8, 0x45, 0x9e,
	0x41, 0x9b, 0x32, 0x41, 0x9f, 0x41, 0xff, 0x96, 0xcf, 0x13, 0x91, 0xf3, 0xa5, 0x2c, 0x53, 0x4d,
	0x07, 0xac, 0xa1, 0x49, 0x46, 0x8f, 0xc0, 0x37, 0x08, 0xa8, 0xd4, 0x46, 0xa5, 0xdd, 0x9a, 0x24,
	0x85, 0x9e, 0xc3, 0x60, 0xc3, 0x5b, 0x95, 0xb9, 0x6e, 0xe0, 0x46, 0xfc, 0xb2, 0xcc, 0x65, 0x55,
	0x26, 0x05, 0xb5, 0x1c, 0x55, 0x95, 0x41, 0x93, 0x62, 0x87, 0xd0, 0xcf, 0x58, 0x35, 0x2f, 0xf3,
	0x42, 0x82, 0x41, 0x57, 0x69, 0x19, 0x10, 0xfd, 0x0e, 0x7c, 0x63, 0x8b, 0x52, 0x3d, 0x25, 0x65,
	0xc0, 0x52, 0x2a, 0x80, 0x2e, 0xfb, 0xbd, 0x60, 0xa5, 0xa8, 0x02, 0x57, 0x1d, 0xb8, 0xde, 0xca,
	0x4f, 0xd7, 0x4b, 0xfc, 0x39, 0xe0, 0xcf, 0x41, 0x43, 0x53, 0x26, 0x86, 0xbf, 0x40, 0x3f, 0xc4,
	0x9d, 0x1a, 0xc2, 0xaf, 0xc1, 0x55, 0xc1, 0xfa, 0xb8, 0x7b, 0x0a, 0x98, 0x64, 0xb5, 0x98, 0x39,
	0x8d, 0x5a, 0x4c, 0xf6, 0x7a, 0x78, 0x07, 0xbb, 0x7a, 0xd0, 0xa7, 0xc9, 0xa2, 0xb8, 0x65, 0xf4,
	0x07, 0x70, 0xae, 0x78, 0xb9, 0x48, 0x04, 0x6a, 0x79, 0x27, 0x07, 0xe3, 0xad, 0xf8, 0xf8, 0xcd,
	0x45, 0xf4, 0xfe, 0x34, 0x8e, 0x34, 0x49, 0xfa, 0x37, 0xe5, 0xd9, 0x1d, 0x2a, 0x0f, 0x22, 0x5c,
	0x0f, 0xbf, 0x05, 0x47, 0xb1, 0x68, 0x0f, 0xda, 0x71, 0xf8, 0x5b, 0x4c, 0x76, 0x68, 0x17, 0xec,
	0x78, 0xfa, 0x81, 0x58, 0x12, 0x7a, 0x3b, 0xbd, 0x38, 0x27, 0xad, 0xe1, 0x3f, 0x1d, 0xf0, 0x1b,
	0x26, 0x93, 0xc7, 0x55, 0xb2, 0x39, 0x2f, 0xb3, 0xd9, 0x9c, 0xaf, 0x96, 0xaa, 0x06, 0x3b, 0xea,
	0x2b, 0xec, 0x4c, 0x42, 0xf2, 0xb8, 0x4c, 0x8a, 0x39, 0x44, 0x06, 0x4d, 0xf6, 0xf8, 0x29, 0xc0,
	0x55, 0x7e, 0xcb, 0xb4, 0x94, 0x8d, 0x52, 0xae, 0x44, 0x94, 0xd0, 0x0b, 0xf0, 0xea, 0xb0, 0x31,
	0x41, 0x83, 0x0d, 0x45, 0x8a, 0x7c, 0x03, 0xbb, 0x95, 0xe0, 0x65, 0x72, 0xcd, 0x66, 0xe9, 0x9d,
	0x60, 0x15, 0x4e, 0x90, 0x1d, 0x0d, 0x34, 0xf8, 0x4a, 0x62, 0xf4, 0x18, 0xf6, 0xb6, 0x48, 0xc6,
	0x0c, 0xf9, 0x26, 0x51, 0x0a, 0x1e, 0x81, 0x53, 0x61, 0x2b, 0x71, 0x7e, 0xfa, 0x27, 0xde, 0x76,
	0x83, 0x23, 0x1d, 0x45, 0x1f, 0xe3, 0xca, 0x98, 0x22, 0x57, 0x21, 0x52, 0xe6, 0x7b, 0x20, 0x2b,
	0xbc, 0xf7, 0x66, 0x9b, 0x8b, 0x3e, 0x70, 0xb1, 0x34, 0x5f, 0xe1, 0xf1, 0x1a, 0xa6, 0x3f, 0xc2,
	0x7e, 0x93, 0x6a, 0x8c, 0x16, 0x6d, 0xd0, 0xb5, 0xfd, 0xe4, 0x71, 0xcc, 0xf4, 0x24, 0xf4, 0xd5,
	0xd8, 0x48, 0xe8, 0x8d, 0x3a, 0xf6, 0x23, 0xf0, 0x0d, 0x02, 0xaa, 0x0d, 0x94, 0xfd, 0x6a, 0xd2,
	0x3d, 0x8e, 0xd9, 0x7d, 0x94, 0x63, 0xbc, 0x7b, 0x1d, 0xd3, 0xb8, 0x12, 0xfc, 0xc7, 0x5c, 0x09,
	0xe4, 0x31, 0x57, 0xc2, 0xde, 0xe3, 0xae, 0x04, 0x7a, 0xef, 0x95, 0x60, 0xf8, 0xf8, 0x8b, 0x07,
	0x7d, 0xbc, 0xff, 0x89, 0x8f, 0x7f, 0x86, 0x4e, 0x28, 0x5f, 0x70, 0xe9, 0xa1, 0x57, 0xd2, 0x43,
	0x96, 0xf2, 0x90, 0x5c, 0xd3, 0x27, 0xd0, 0x8e, 0xef, 0x0a, 0xe5, 0x58, 0xef, 0xa4, 0x33, 0x96,
	0x9b, 0x08, 0xa1, 0xe3, 0x11, 0x74, 0xa6, 0xf1, 0x69, 0x1c, 0x4a, 0x2b, 0x9d, 0x5f, 0x9c, 0x87,
	0x64, 0x87, 0xba, 0xd0, 0xf9, 0x70, 0xfa, 0xee, 0x32, 0x24, 0x16, 0x05, 0x70, 0x5e, 0x87, 0xef,
	0xc2, 0x38, 0x24, 0xad, 0xe3, 0xbf, 0x2c, 0xa5, 0x82, 0x4c, 0xbe, 0x64, 0x64, 0x87, 0x06, 0xb0,
	0x8f, 0x49, 0x67, 0xdb, 0xff, 0x05, 0x88, 0x55, 0x47, 0xb6, 0xdf, 0x77, 0xd2, 0xfa, 0x24, 0xa2,
	0xdf, 0x5b, 0x62, 0xd3, 0x03, 0xd8, 0x53, 0x11, 0xe3, 0x42, 0x22, 0x6d, 0x4a, 0xc1, 0x53, 0xf0,
	0xfa, 0xa5, 0x24, 0x9d, 0x5a, 0x64, 0xfb, 0xb9, 0x22, 0x4e, 0xea, 0xe0, 0xff, 0x93, 0x9f, 0xfe,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xa6, 0x71, 0x15, 0xd0, 0x08, 0x00, 0x00,
}
