// Code generated by protoc-gen-go.
// source: mlp_api.proto
// DO NOT EDIT!

/*
Package mlp_api is a generated protocol buffer package.

It is generated from these files:
	mlp_api.proto

It has these top-level messages:
	CreateProjectRequest
	GetProjectRequest
	ProjectInfoResponse
	CreateJobRequest
	GetJobRequest
	JobInfoResponse
	StartJobRunRequest
	JobRunInfoResponse
	LogJobRunRequest
	FailJobRunRequest
	CompleteJobRunRequest
	CreateServiceRequest
	GetServiceRequest
	ServiceInfoResponse
	AddServiceVersionRequest
	AddServiceVersionResponse
	GetDatasetRequest
	CreateDatasetRequest
	DatasetInfoResponse
	GetLastDatasetVersionRequest
	DatasetVersionResponse
	DatasetChangeSet
	DatasetCommit
	CommitRequest
	CommitResponse
	StatRequest
	StatResponse
	UpdateDatasetRequest
	ApiError
	EmptyResponse
*/
package mlp_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import vo "mlp/catalog/vo"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	// codes in gRPC
	StatusCode_OK StatusCode = 0
	// The operation was cancelled, typically by the caller.
	StatusCode_CANCELLED StatusCode = 1
	// Unknown error.  For example, this error may be returned when
	// a `Status` value received from another address space belongs to
	// an error space that is not known in this address space.  Also
	// errors raised by APIs that do not return enough error information
	// may be converted to this error.
	StatusCode_UNKNOWN StatusCode = 2
	// The client specified an invalid argument.  Note that this differs
	// from `FAILED_PRECONDITION`.  `INVALID_ARGUMENT` indicates arguments
	// that are problematic regardless of the state of the system
	// (e.g., a malformed file name).
	//
	// HTTP Mapping: 400 Bad Request
	StatusCode_INVALID_ARGUMENT StatusCode = 3
	// The deadline expired before the operation could complete. For operations
	// that change the state of the system, this error may be returned
	// even if the operation has completed successfully.  For example, a
	// successful response from a server could have been delayed long
	// enough for the deadline to expire.
	StatusCode_DEADLINE_EXCEEDED StatusCode = 4
	StatusCode_NOT_FOUND         StatusCode = 5
	// The entity that a client attempted to create (e.g., file or directory)
	// already exists.
	StatusCode_ALREADY_EXISTS StatusCode = 6
	// The caller does not have permission to execute the specified
	// operation. `PERMISSION_DENIED` must not be used for rejections
	// caused by exhausting some resource (use `RESOURCE_EXHAUSTED`
	// instead for those errors). `PERMISSION_DENIED` must not be
	// used if the caller can not be identified (use `UNAUTHENTICATED`
	// instead for those errors). This error code does not imply the
	// request is valid or the requested entity exists or satisfies
	// other pre-conditions.
	StatusCode_PERMISSION_DENIED StatusCode = 7
	// The request does not have valid authentication credentials for the
	// operation.
	StatusCode_UNAUTHENTICATED StatusCode = 16
	// Some resource has been exhausted, perhaps a per-user quota, or
	// perhaps the entire file system is out of space.
	StatusCode_RESOURCE_EXHAUSTED StatusCode = 8
	// The operation was rejected because the system is not in a state
	// required for the operation's execution.  For example, the directory
	// to be deleted is non-empty, an rmdir operation is applied to
	// a non-directory, etc.
	//
	// Service implementors can use the following guidelines to decide
	// between `FAILED_PRECONDITION`, `ABORTED`, and `UNAVAILABLE`:
	//  (a) Use `UNAVAILABLE` if the client can retry just the failing call.
	//  (b) Use `ABORTED` if the client should retry at a higher level
	//      (e.g., when a client-specified test-and-set fails, indicating the
	//      client should restart a read-modify-write sequence).
	//  (c) Use `FAILED_PRECONDITION` if the client should not retry until
	//      the system state has been explicitly fixed.  E.g., if an "rmdir"
	//      fails because the directory is non-empty, `FAILED_PRECONDITION`
	//      should be returned since the client should not retry unless
	//      the files are deleted from the directory.
	//
	// HTTP Mapping: 400 Bad Request
	StatusCode_FAILED_PRECONDITION StatusCode = 9
	// The operation was aborted, typically due to a concurrency issue such as
	// a sequencer check failure or transaction abort.
	StatusCode_ABORTED StatusCode = 10
	// The operation was attempted past the valid range.  E.g., seeking or
	// reading past end-of-file.
	StatusCode_OUT_OF_RANGE StatusCode = 11
	// The operation is not implemented or is not supported/enabled in this
	// service.
	//
	// HTTP Mapping: 501 Not Implemented
	StatusCode_UNIMPLEMENTED StatusCode = 12
	StatusCode_INTERNAL      StatusCode = 13
	// The service is currently unavailable.  This is most likely a
	// transient condition, which can be corrected by retrying with
	// a backoff.
	StatusCode_UNAVAILABLE StatusCode = 14
	// Unrecoverable data loss or corruption.
	StatusCode_DATA_LOSS StatusCode = 15
	// Bad entity name was supplied
	StatusCode_BAD_NAME         StatusCode = 100
	StatusCode_NAME_TAKEN       StatusCode = 101
	StatusCode_VERSION_MISMATCH StatusCode = 102
)

var StatusCode_name = map[int32]string{
	0:   "OK",
	1:   "CANCELLED",
	2:   "UNKNOWN",
	3:   "INVALID_ARGUMENT",
	4:   "DEADLINE_EXCEEDED",
	5:   "NOT_FOUND",
	6:   "ALREADY_EXISTS",
	7:   "PERMISSION_DENIED",
	16:  "UNAUTHENTICATED",
	8:   "RESOURCE_EXHAUSTED",
	9:   "FAILED_PRECONDITION",
	10:  "ABORTED",
	11:  "OUT_OF_RANGE",
	12:  "UNIMPLEMENTED",
	13:  "INTERNAL",
	14:  "UNAVAILABLE",
	15:  "DATA_LOSS",
	100: "BAD_NAME",
	101: "NAME_TAKEN",
	102: "VERSION_MISMATCH",
}
var StatusCode_value = map[string]int32{
	"OK":                  0,
	"CANCELLED":           1,
	"UNKNOWN":             2,
	"INVALID_ARGUMENT":    3,
	"DEADLINE_EXCEEDED":   4,
	"NOT_FOUND":           5,
	"ALREADY_EXISTS":      6,
	"PERMISSION_DENIED":   7,
	"UNAUTHENTICATED":     16,
	"RESOURCE_EXHAUSTED":  8,
	"FAILED_PRECONDITION": 9,
	"ABORTED":             10,
	"OUT_OF_RANGE":        11,
	"UNIMPLEMENTED":       12,
	"INTERNAL":            13,
	"UNAVAILABLE":         14,
	"DATA_LOSS":           15,
	"BAD_NAME":            100,
	"NAME_TAKEN":          101,
	"VERSION_MISMATCH":    102,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// PROJECT
type CreateProjectRequest struct {
	Name string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Meta *vo.ProjectMetadataDelta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *CreateProjectRequest) Reset()                    { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()               {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateProjectRequest) GetMeta() *vo.ProjectMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type GetProjectRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetProjectRequest) Reset()                    { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()               {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ProjectInfoResponse struct {
	Uid   []byte    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name  string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Error *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *ProjectInfoResponse) Reset()                    { *m = ProjectInfoResponse{} }
func (m *ProjectInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*ProjectInfoResponse) ProtoMessage()               {}
func (*ProjectInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProjectInfoResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

// JOB -----------------------------------
type CreateJobRequest struct {
	ProjectUid []byte               `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name       string               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Meta       *vo.JobMetadataDelta `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
}

func (m *CreateJobRequest) Reset()                    { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()               {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateJobRequest) GetMeta() *vo.JobMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type GetJobRequest struct {
	ProjectUid []byte `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *GetJobRequest) Reset()                    { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string            { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()               {}
func (*GetJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type JobInfoResponse struct {
	Name        string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Uid         []byte    `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ProjectName string    `protobuf:"bytes,3,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectUid  []byte    `protobuf:"bytes,4,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Error       *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *JobInfoResponse) Reset()                    { *m = JobInfoResponse{} }
func (m *JobInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*JobInfoResponse) ProtoMessage()               {}
func (*JobInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *JobInfoResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type StartJobRunRequest struct {
	ProjectUid []byte            `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	JobUid     []byte            `protobuf:"bytes,2,opt,name=job_uid,json=jobUid,proto3" json:"job_uid,omitempty"`
	Title      string            `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Inputs     []*vo.JobRunInput `protobuf:"bytes,4,rep,name=inputs" json:"inputs,omitempty"`
}

func (m *StartJobRunRequest) Reset()                    { *m = StartJobRunRequest{} }
func (m *StartJobRunRequest) String() string            { return proto.CompactTextString(m) }
func (*StartJobRunRequest) ProtoMessage()               {}
func (*StartJobRunRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StartJobRunRequest) GetInputs() []*vo.JobRunInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

type JobRunInfoResponse struct {
	Uid        []byte    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProjectUid []byte    `protobuf:"bytes,2,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Error      *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *JobRunInfoResponse) Reset()                    { *m = JobRunInfoResponse{} }
func (m *JobRunInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*JobRunInfoResponse) ProtoMessage()               {}
func (*JobRunInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *JobRunInfoResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type LogJobRunRequest struct {
	Uid     []byte `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Details string `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
	// optional title for the log
	LogTitle string `protobuf:"bytes,3,opt,name=log_title,json=logTitle" json:"log_title,omitempty"`
}

func (m *LogJobRunRequest) Reset()                    { *m = LogJobRunRequest{} }
func (m *LogJobRunRequest) String() string            { return proto.CompactTextString(m) }
func (*LogJobRunRequest) ProtoMessage()               {}
func (*LogJobRunRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// returns OkResponse
type FailJobRunRequest struct {
	Uid     []byte `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Details string `protobuf:"bytes,3,opt,name=details" json:"details,omitempty"`
}

func (m *FailJobRunRequest) Reset()                    { *m = FailJobRunRequest{} }
func (m *FailJobRunRequest) String() string            { return proto.CompactTextString(m) }
func (*FailJobRunRequest) ProtoMessage()               {}
func (*FailJobRunRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// returns OkResponse
type CompleteJobRunRequest struct {
	Uid []byte `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (m *CompleteJobRunRequest) Reset()                    { *m = CompleteJobRunRequest{} }
func (m *CompleteJobRunRequest) String() string            { return proto.CompactTextString(m) }
func (*CompleteJobRunRequest) ProtoMessage()               {}
func (*CompleteJobRunRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type CreateServiceRequest struct {
	ProjectUid []byte                   `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name       string                   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Meta       *vo.ServiceMetadataDelta `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
}

func (m *CreateServiceRequest) Reset()                    { *m = CreateServiceRequest{} }
func (m *CreateServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateServiceRequest) ProtoMessage()               {}
func (*CreateServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateServiceRequest) GetMeta() *vo.ServiceMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type GetServiceRequest struct {
	ProjectUid []byte `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *GetServiceRequest) Reset()                    { *m = GetServiceRequest{} }
func (m *GetServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*GetServiceRequest) ProtoMessage()               {}
func (*GetServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type ServiceInfoResponse struct {
	Uid         []byte    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProjectUid  []byte    `protobuf:"bytes,2,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name        string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ProjectName string    `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	Error       *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *ServiceInfoResponse) Reset()                    { *m = ServiceInfoResponse{} }
func (m *ServiceInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceInfoResponse) ProtoMessage()               {}
func (*ServiceInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ServiceInfoResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type AddServiceVersionRequest struct {
	ServiceUid []byte                     `protobuf:"bytes,1,opt,name=service_uid,json=serviceUid,proto3" json:"service_uid,omitempty"`
	Title      string                     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Inputs     []*vo.ServiceVersionInput  `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty"`
	Outputs    []*vo.ServiceVersionOutput `protobuf:"bytes,4,rep,name=outputs" json:"outputs,omitempty"`
}

func (m *AddServiceVersionRequest) Reset()                    { *m = AddServiceVersionRequest{} }
func (m *AddServiceVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*AddServiceVersionRequest) ProtoMessage()               {}
func (*AddServiceVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AddServiceVersionRequest) GetInputs() []*vo.ServiceVersionInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *AddServiceVersionRequest) GetOutputs() []*vo.ServiceVersionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type AddServiceVersionResponse struct {
	Uid   []byte    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Error *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *AddServiceVersionResponse) Reset()                    { *m = AddServiceVersionResponse{} }
func (m *AddServiceVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*AddServiceVersionResponse) ProtoMessage()               {}
func (*AddServiceVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *AddServiceVersionResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

// -> DatasetResponse
type GetDatasetRequest struct {
	ProjectUid []byte `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *GetDatasetRequest) Reset()                    { *m = GetDatasetRequest{} }
func (m *GetDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDatasetRequest) ProtoMessage()               {}
func (*GetDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type CreateDatasetRequest struct {
	ProjectUid []byte                   `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name       string                   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Meta       *vo.DatasetMetadataDelta `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
}

func (m *CreateDatasetRequest) Reset()                    { *m = CreateDatasetRequest{} }
func (m *CreateDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDatasetRequest) ProtoMessage()               {}
func (*CreateDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CreateDatasetRequest) GetMeta() *vo.DatasetMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type DatasetInfoResponse struct {
	Uid             []byte    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProjectUid      []byte    `protobuf:"bytes,2,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name            string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ProjectName     string    `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	UpdateTimestamp int64     `protobuf:"varint,9,opt,name=update_timestamp,json=updateTimestamp" json:"update_timestamp,omitempty"`
	DataFormat      string    `protobuf:"bytes,10,opt,name=data_format,json=dataFormat" json:"data_format,omitempty"`
	Description     string    `protobuf:"bytes,11,opt,name=description" json:"description,omitempty"`
	LocationId      string    `protobuf:"bytes,12,opt,name=location_id,json=locationId" json:"location_id,omitempty"`
	LocationUri     string    `protobuf:"bytes,13,opt,name=location_uri,json=locationUri" json:"location_uri,omitempty"`
	Error           *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *DatasetInfoResponse) Reset()                    { *m = DatasetInfoResponse{} }
func (m *DatasetInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*DatasetInfoResponse) ProtoMessage()               {}
func (*DatasetInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DatasetInfoResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

// DATASET VERSION -----------------
type GetLastDatasetVersionRequest struct {
	ProjectUid []byte `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	DatasetUid []byte `protobuf:"bytes,2,opt,name=dataset_uid,json=datasetUid,proto3" json:"dataset_uid,omitempty"`
}

func (m *GetLastDatasetVersionRequest) Reset()                    { *m = GetLastDatasetVersionRequest{} }
func (m *GetLastDatasetVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLastDatasetVersionRequest) ProtoMessage()               {}
func (*GetLastDatasetVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type DatasetVersionResponse struct {
	Uid       []byte    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NoVersion bool      `protobuf:"varint,2,opt,name=no_version,json=noVersion" json:"no_version,omitempty"`
	Error     *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *DatasetVersionResponse) Reset()                    { *m = DatasetVersionResponse{} }
func (m *DatasetVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*DatasetVersionResponse) ProtoMessage()               {}
func (*DatasetVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DatasetVersionResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

// creates a new version
type DatasetChangeSet struct {
	DatasetUid       []byte `protobuf:"bytes,1,opt,name=dataset_uid,json=datasetUid,proto3" json:"dataset_uid,omitempty"`
	ParentVersionUid []byte `protobuf:"bytes,2,opt,name=parent_version_uid,json=parentVersionUid,proto3" json:"parent_version_uid,omitempty"`
	// items are added to the same location
	Items      []*vo.DatasetItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	CleanSlate bool              `protobuf:"varint,4,opt,name=clean_slate,json=cleanSlate" json:"clean_slate,omitempty"`
	Remove     []string          `protobuf:"bytes,5,rep,name=remove" json:"remove,omitempty"`
	// inputs to mark
	Inputs []*vo.DatasetVerInput `protobuf:"bytes,6,rep,name=inputs" json:"inputs,omitempty"`
}

func (m *DatasetChangeSet) Reset()                    { *m = DatasetChangeSet{} }
func (m *DatasetChangeSet) String() string            { return proto.CompactTextString(m) }
func (*DatasetChangeSet) ProtoMessage()               {}
func (*DatasetChangeSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *DatasetChangeSet) GetItems() []*vo.DatasetItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *DatasetChangeSet) GetInputs() []*vo.DatasetVerInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

type DatasetCommit struct {
	Title    string              `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Datasets []*DatasetChangeSet `protobuf:"bytes,2,rep,name=datasets" json:"datasets,omitempty"`
}

func (m *DatasetCommit) Reset()                    { *m = DatasetCommit{} }
func (m *DatasetCommit) String() string            { return proto.CompactTextString(m) }
func (*DatasetCommit) ProtoMessage()               {}
func (*DatasetCommit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *DatasetCommit) GetDatasets() []*DatasetChangeSet {
	if m != nil {
		return m.Datasets
	}
	return nil
}

// commit multiple changes in one transaction
type CommitRequest struct {
	Title    string              `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Datasets []*DatasetChangeSet `protobuf:"bytes,7,rep,name=datasets" json:"datasets,omitempty"`
}

func (m *CommitRequest) Reset()                    { *m = CommitRequest{} }
func (m *CommitRequest) String() string            { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()               {}
func (*CommitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CommitRequest) GetDatasets() []*DatasetChangeSet {
	if m != nil {
		return m.Datasets
	}
	return nil
}

type CommitResponse struct {
	DatasetVersions [][]byte  `protobuf:"bytes,1,rep,name=dataset_versions,json=datasetVersions,proto3" json:"dataset_versions,omitempty"`
	Error           *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *CommitResponse) Reset()                    { *m = CommitResponse{} }
func (m *CommitResponse) String() string            { return proto.CompactTextString(m) }
func (*CommitResponse) ProtoMessage()               {}
func (*CommitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CommitResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type StatRequest struct {
}

func (m *StatRequest) Reset()                    { *m = StatRequest{} }
func (m *StatRequest) String() string            { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()               {}
func (*StatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type StatResponse struct {
	Version string    `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Error   *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *StatResponse) Reset()                    { *m = StatResponse{} }
func (m *StatResponse) String() string            { return proto.CompactTextString(m) }
func (*StatResponse) ProtoMessage()               {}
func (*StatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *StatResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type UpdateDatasetRequest struct {
	// option 1
	Uid  []byte                   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Meta *vo.DatasetMetadataDelta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *UpdateDatasetRequest) Reset()                    { *m = UpdateDatasetRequest{} }
func (m *UpdateDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDatasetRequest) ProtoMessage()               {}
func (*UpdateDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *UpdateDatasetRequest) GetMeta() *vo.DatasetMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ApiError struct {
	Code    StatusCode `protobuf:"varint,1,opt,name=code,enum=StatusCode" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// For API matching and tests
	SubjectUid  []byte   `protobuf:"bytes,3,opt,name=subject_uid,json=subjectUid,proto3" json:"subject_uid,omitempty"`
	SubjectName string   `protobuf:"bytes,4,opt,name=subject_name,json=subjectName" json:"subject_name,omitempty"`
	FieldName   string   `protobuf:"bytes,5,opt,name=field_name,json=fieldName" json:"field_name,omitempty"`
	Details     []string `protobuf:"bytes,6,rep,name=details" json:"details,omitempty"`
	ProjectName string   `protobuf:"bytes,7,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectUid  string   `protobuf:"bytes,8,opt,name=project_uid,json=projectUid" json:"project_uid,omitempty"`
	MethodName  string   `protobuf:"bytes,9,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
}

func (m *ApiError) Reset()                    { *m = ApiError{} }
func (m *ApiError) String() string            { return proto.CompactTextString(m) }
func (*ApiError) ProtoMessage()               {}
func (*ApiError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type EmptyResponse struct {
	Error *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *EmptyResponse) Reset()                    { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()               {}
func (*EmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *EmptyResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateProjectRequest)(nil), "CreateProjectRequest")
	proto.RegisterType((*GetProjectRequest)(nil), "GetProjectRequest")
	proto.RegisterType((*ProjectInfoResponse)(nil), "ProjectInfoResponse")
	proto.RegisterType((*CreateJobRequest)(nil), "CreateJobRequest")
	proto.RegisterType((*GetJobRequest)(nil), "GetJobRequest")
	proto.RegisterType((*JobInfoResponse)(nil), "JobInfoResponse")
	proto.RegisterType((*StartJobRunRequest)(nil), "StartJobRunRequest")
	proto.RegisterType((*JobRunInfoResponse)(nil), "JobRunInfoResponse")
	proto.RegisterType((*LogJobRunRequest)(nil), "LogJobRunRequest")
	proto.RegisterType((*FailJobRunRequest)(nil), "FailJobRunRequest")
	proto.RegisterType((*CompleteJobRunRequest)(nil), "CompleteJobRunRequest")
	proto.RegisterType((*CreateServiceRequest)(nil), "CreateServiceRequest")
	proto.RegisterType((*GetServiceRequest)(nil), "GetServiceRequest")
	proto.RegisterType((*ServiceInfoResponse)(nil), "ServiceInfoResponse")
	proto.RegisterType((*AddServiceVersionRequest)(nil), "AddServiceVersionRequest")
	proto.RegisterType((*AddServiceVersionResponse)(nil), "AddServiceVersionResponse")
	proto.RegisterType((*GetDatasetRequest)(nil), "GetDatasetRequest")
	proto.RegisterType((*CreateDatasetRequest)(nil), "CreateDatasetRequest")
	proto.RegisterType((*DatasetInfoResponse)(nil), "DatasetInfoResponse")
	proto.RegisterType((*GetLastDatasetVersionRequest)(nil), "GetLastDatasetVersionRequest")
	proto.RegisterType((*DatasetVersionResponse)(nil), "DatasetVersionResponse")
	proto.RegisterType((*DatasetChangeSet)(nil), "DatasetChangeSet")
	proto.RegisterType((*DatasetCommit)(nil), "DatasetCommit")
	proto.RegisterType((*CommitRequest)(nil), "CommitRequest")
	proto.RegisterType((*CommitResponse)(nil), "CommitResponse")
	proto.RegisterType((*StatRequest)(nil), "StatRequest")
	proto.RegisterType((*StatResponse)(nil), "StatResponse")
	proto.RegisterType((*UpdateDatasetRequest)(nil), "UpdateDatasetRequest")
	proto.RegisterType((*ApiError)(nil), "ApiError")
	proto.RegisterType((*EmptyResponse)(nil), "EmptyResponse")
	proto.RegisterEnum("StatusCode", StatusCode_name, StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Catalog service

type CatalogClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectInfoResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectInfoResponse, error)
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceInfoResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceInfoResponse, error)
	AddServiceVersion(ctx context.Context, in *AddServiceVersionRequest, opts ...grpc.CallOption) (*AddServiceVersionResponse, error)
	// JOBS -----------------
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error)
	StartJobRun(ctx context.Context, in *StartJobRunRequest, opts ...grpc.CallOption) (*JobRunInfoResponse, error)
	LogJobRun(ctx context.Context, in *LogJobRunRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	FailJobRun(ctx context.Context, in *FailJobRunRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	CompleteJobRun(ctx context.Context, in *CompleteJobRunRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*DatasetInfoResponse, error)
	GetDataset(ctx context.Context, in *GetDatasetRequest, opts ...grpc.CallOption) (*DatasetInfoResponse, error)
	UpdateDataset(ctx context.Context, in *UpdateDatasetRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetLastDatasetVersion(ctx context.Context, in *GetLastDatasetVersionRequest, opts ...grpc.CallOption) (*DatasetVersionResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
}

type catalogClient struct {
	cc *grpc.ClientConn
}

func NewCatalogClient(cc *grpc.ClientConn) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectInfoResponse, error) {
	out := new(ProjectInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/CreateProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectInfoResponse, error) {
	out := new(ProjectInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/GetProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceInfoResponse, error) {
	out := new(ServiceInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/CreateService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceInfoResponse, error) {
	out := new(ServiceInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/GetService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) AddServiceVersion(ctx context.Context, in *AddServiceVersionRequest, opts ...grpc.CallOption) (*AddServiceVersionResponse, error) {
	out := new(AddServiceVersionResponse)
	err := grpc.Invoke(ctx, "/Catalog/AddServiceVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error) {
	out := new(JobInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/CreateJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error) {
	out := new(JobInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/GetJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) StartJobRun(ctx context.Context, in *StartJobRunRequest, opts ...grpc.CallOption) (*JobRunInfoResponse, error) {
	out := new(JobRunInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/StartJobRun", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) LogJobRun(ctx context.Context, in *LogJobRunRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/Catalog/LogJobRun", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) FailJobRun(ctx context.Context, in *FailJobRunRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/Catalog/FailJobRun", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) CompleteJobRun(ctx context.Context, in *CompleteJobRunRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/Catalog/CompleteJobRun", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*DatasetInfoResponse, error) {
	out := new(DatasetInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/CreateDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetDataset(ctx context.Context, in *GetDatasetRequest, opts ...grpc.CallOption) (*DatasetInfoResponse, error) {
	out := new(DatasetInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/GetDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) UpdateDataset(ctx context.Context, in *UpdateDatasetRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/Catalog/UpdateDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetLastDatasetVersion(ctx context.Context, in *GetLastDatasetVersionRequest, opts ...grpc.CallOption) (*DatasetVersionResponse, error) {
	out := new(DatasetVersionResponse)
	err := grpc.Invoke(ctx, "/Catalog/GetLastDatasetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := grpc.Invoke(ctx, "/Catalog/Commit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	out := new(StatResponse)
	err := grpc.Invoke(ctx, "/Catalog/Stat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Catalog service

type CatalogServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*ProjectInfoResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*ProjectInfoResponse, error)
	CreateService(context.Context, *CreateServiceRequest) (*ServiceInfoResponse, error)
	GetService(context.Context, *GetServiceRequest) (*ServiceInfoResponse, error)
	AddServiceVersion(context.Context, *AddServiceVersionRequest) (*AddServiceVersionResponse, error)
	// JOBS -----------------
	CreateJob(context.Context, *CreateJobRequest) (*JobInfoResponse, error)
	GetJob(context.Context, *GetJobRequest) (*JobInfoResponse, error)
	StartJobRun(context.Context, *StartJobRunRequest) (*JobRunInfoResponse, error)
	LogJobRun(context.Context, *LogJobRunRequest) (*EmptyResponse, error)
	FailJobRun(context.Context, *FailJobRunRequest) (*EmptyResponse, error)
	CompleteJobRun(context.Context, *CompleteJobRunRequest) (*EmptyResponse, error)
	CreateDataset(context.Context, *CreateDatasetRequest) (*DatasetInfoResponse, error)
	GetDataset(context.Context, *GetDatasetRequest) (*DatasetInfoResponse, error)
	UpdateDataset(context.Context, *UpdateDatasetRequest) (*EmptyResponse, error)
	GetLastDatasetVersion(context.Context, *GetLastDatasetVersionRequest) (*DatasetVersionResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
}

func RegisterCatalogServer(s *grpc.Server, srv CatalogServer) {
	s.RegisterService(&_Catalog_serviceDesc, srv)
}

func _Catalog_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_AddServiceVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServiceVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).AddServiceVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/AddServiceVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).AddServiceVersion(ctx, req.(*AddServiceVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_StartJobRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJobRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).StartJobRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/StartJobRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).StartJobRun(ctx, req.(*StartJobRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_LogJobRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogJobRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).LogJobRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/LogJobRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).LogJobRun(ctx, req.(*LogJobRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_FailJobRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailJobRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).FailJobRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/FailJobRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).FailJobRun(ctx, req.(*FailJobRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_CompleteJobRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CompleteJobRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CompleteJobRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CompleteJobRun(ctx, req.(*CompleteJobRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_CreateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CreateDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateDataset(ctx, req.(*CreateDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/GetDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetDataset(ctx, req.(*GetDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_UpdateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).UpdateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/UpdateDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).UpdateDataset(ctx, req.(*UpdateDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetLastDatasetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastDatasetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetLastDatasetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/GetLastDatasetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetLastDatasetVersion(ctx, req.(*GetLastDatasetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Catalog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _Catalog_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _Catalog_GetProject_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _Catalog_CreateService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _Catalog_GetService_Handler,
		},
		{
			MethodName: "AddServiceVersion",
			Handler:    _Catalog_AddServiceVersion_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _Catalog_CreateJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _Catalog_GetJob_Handler,
		},
		{
			MethodName: "StartJobRun",
			Handler:    _Catalog_StartJobRun_Handler,
		},
		{
			MethodName: "LogJobRun",
			Handler:    _Catalog_LogJobRun_Handler,
		},
		{
			MethodName: "FailJobRun",
			Handler:    _Catalog_FailJobRun_Handler,
		},
		{
			MethodName: "CompleteJobRun",
			Handler:    _Catalog_CompleteJobRun_Handler,
		},
		{
			MethodName: "CreateDataset",
			Handler:    _Catalog_CreateDataset_Handler,
		},
		{
			MethodName: "GetDataset",
			Handler:    _Catalog_GetDataset_Handler,
		},
		{
			MethodName: "UpdateDataset",
			Handler:    _Catalog_UpdateDataset_Handler,
		},
		{
			MethodName: "GetLastDatasetVersion",
			Handler:    _Catalog_GetLastDatasetVersion_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Catalog_Commit_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Catalog_Stat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("mlp_api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x58, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0xd6, 0xc9, 0x3a, 0x8c, 0x0e, 0xa6, 0xd6, 0x96, 0xa3, 0xe8, 0xff, 0x83, 0xf8, 0x27, 0xfe,
	0xa0, 0x76, 0x9b, 0x6e, 0x03, 0xf7, 0xa6, 0xed, 0x45, 0x01, 0x46, 0xa4, 0x6d, 0x26, 0x32, 0xe5,
	0x52, 0xa2, 0x9b, 0xa0, 0x01, 0x58, 0xda, 0x5a, 0x3b, 0x34, 0x24, 0x51, 0x25, 0x57, 0x06, 0xfa,
	0x0a, 0x7d, 0x86, 0x5e, 0xf4, 0xae, 0xb7, 0x7d, 0x96, 0xbe, 0x43, 0x81, 0xde, 0xf6, 0x0d, 0x8a,
	0x5d, 0x1e, 0x44, 0x4a, 0xb4, 0xe5, 0xc2, 0x01, 0x7a, 0xc7, 0x9d, 0x9d, 0xfd, 0xe6, 0xb0, 0x33,
	0xb3, 0x33, 0x84, 0xfa, 0x64, 0x3c, 0x33, 0xad, 0x99, 0x8d, 0x67, 0xae, 0x43, 0x9d, 0x4e, 0xf9,
	0xc6, 0xf1, 0xbf, 0x44, 0x03, 0xb6, 0xbb, 0x2e, 0xb1, 0x28, 0x39, 0x75, 0x9d, 0x6b, 0x72, 0x41,
	0x75, 0xf2, 0xc3, 0x9c, 0x78, 0x14, 0x21, 0x28, 0x4c, 0xad, 0x09, 0x69, 0x67, 0x77, 0xb3, 0x7b,
	0x15, 0x9d, 0x7f, 0xa3, 0x7d, 0x28, 0x4c, 0x08, 0xb5, 0xda, 0xb9, 0xdd, 0xec, 0x5e, 0xf5, 0xa0,
	0x85, 0x83, 0x23, 0x27, 0x84, 0x5a, 0x23, 0x8b, 0x5a, 0x32, 0x19, 0x53, 0x4b, 0xe7, 0x2c, 0xe2,
	0x47, 0xd0, 0x3c, 0x22, 0x74, 0x3d, 0xa6, 0xf8, 0x0e, 0xb6, 0x02, 0x2e, 0x75, 0x7a, 0xe9, 0xe8,
	0xc4, 0x9b, 0x39, 0x53, 0x8f, 0x20, 0x01, 0xf2, 0x73, 0x7b, 0xc4, 0x39, 0x6b, 0x3a, 0xfb, 0x8c,
	0x0e, 0xe7, 0x62, 0x0a, 0x3d, 0x85, 0x0d, 0xe2, 0xba, 0x8e, 0xdb, 0x1e, 0x71, 0x8d, 0x2a, 0x58,
	0x9a, 0xd9, 0x0a, 0x23, 0xe8, 0x3e, 0x5d, 0x9c, 0x82, 0xe0, 0x5b, 0xf7, 0xca, 0x39, 0x0f, 0xb5,
	0x78, 0x0a, 0xd5, 0x99, 0x2f, 0xd1, 0x5c, 0x88, 0x80, 0x80, 0x64, 0xdc, 0x22, 0xe9, 0x59, 0x60,
	0x7a, 0x9e, 0x0b, 0x6a, 0xe2, 0x57, 0xce, 0x79, 0x9a, 0xd9, 0x32, 0xd4, 0x8f, 0x08, 0x7d, 0xa0,
	0x30, 0xf1, 0xe7, 0x2c, 0x6c, 0xbe, 0x72, 0xce, 0x13, 0x0e, 0x49, 0xbb, 0x8f, 0xc0, 0x49, 0xb9,
	0x85, 0x93, 0xfe, 0x07, 0xb5, 0x50, 0x1c, 0xe7, 0xce, 0x73, 0xee, 0x50, 0x05, 0xcd, 0xf7, 0x59,
	0x42, 0xa3, 0xc2, 0x8a, 0x46, 0x6b, 0x9d, 0xfa, 0x53, 0x16, 0xd0, 0x80, 0x5a, 0x2e, 0xb7, 0x73,
	0x3e, 0xbd, 0xb7, 0xa9, 0x8f, 0xa0, 0x74, 0xed, 0x9c, 0x9b, 0x0b, 0x95, 0x8b, 0xd7, 0xce, 0x39,
	0xdb, 0xd8, 0x86, 0x0d, 0x6a, 0xd3, 0x71, 0xa8, 0xae, 0xbf, 0x40, 0xff, 0x87, 0xa2, 0x3d, 0x9d,
	0xcd, 0xa9, 0xd7, 0x2e, 0xec, 0xe6, 0xf7, 0xaa, 0x07, 0x35, 0xec, 0xcb, 0x53, 0x19, 0x51, 0x0f,
	0xf6, 0xc4, 0xf7, 0x80, 0x42, 0xf2, 0x9d, 0xe1, 0xb3, 0xa4, 0x5d, 0xee, 0x9f, 0x9b, 0xfd, 0x1d,
	0x08, 0x3d, 0xe7, 0x2a, 0x69, 0xf3, 0xaa, 0x9c, 0x36, 0x94, 0x46, 0x84, 0x5a, 0xf6, 0xd8, 0x0b,
	0xae, 0x34, 0x5c, 0xa2, 0xff, 0x40, 0x65, 0xec, 0x5c, 0x99, 0x71, 0x4b, 0xcb, 0x63, 0xe7, 0x6a,
	0xc8, 0xd6, 0xe2, 0x5b, 0x68, 0x1e, 0x5a, 0xf6, 0xf8, 0x1e, 0xe8, 0x13, 0xe2, 0x79, 0xd6, 0x55,
	0x18, 0x30, 0xe1, 0x32, 0x2e, 0x37, 0x9f, 0x90, 0x2b, 0xee, 0x43, 0xab, 0xeb, 0x4c, 0x66, 0x63,
	0xe2, 0x67, 0xc1, 0x1d, 0xf0, 0xe2, 0x4d, 0x58, 0x0c, 0x06, 0xc4, 0xbd, 0xb1, 0x2f, 0xc8, 0x83,
	0x52, 0x66, 0x3f, 0x91, 0x32, 0x2d, 0x1c, 0x60, 0xa6, 0xa5, 0xcd, 0x31, 0xaf, 0x16, 0x1f, 0x40,
	0xa8, 0xf8, 0x4b, 0x16, 0xb6, 0x02, 0x9c, 0x87, 0x06, 0x44, 0x08, 0x9f, 0x8f, 0xd9, 0xb4, 0x9c,
	0x5f, 0x85, 0xb4, 0xfc, 0x5a, 0x13, 0x47, 0xbf, 0x65, 0xa1, 0x2d, 0x8d, 0x46, 0x81, 0x96, 0x67,
	0xc4, 0xf5, 0x6c, 0x27, 0x9e, 0x44, 0x9e, 0xbf, 0x11, 0x37, 0x3a, 0x20, 0x25, 0x72, 0x25, 0x17,
	0xcf, 0x95, 0xe7, 0x51, 0xae, 0xe4, 0x79, 0xae, 0x6c, 0xe3, 0x24, 0x7c, 0x22, 0x67, 0xd0, 0x67,
	0x50, 0x72, 0xe6, 0x34, 0x96, 0x5a, 0xad, 0x25, 0xf6, 0x3e, 0xdf, 0xd5, 0x43, 0x2e, 0x51, 0x83,
	0xc7, 0x29, 0x1a, 0xdf, 0xe1, 0xda, 0x35, 0x2e, 0xf0, 0xef, 0x5b, 0xb6, 0xa8, 0xe5, 0x11, 0xfa,
	0xa0, 0xfb, 0x8e, 0x22, 0xf6, 0x03, 0x80, 0xad, 0x44, 0x6c, 0x80, 0x99, 0x16, 0xb1, 0xbf, 0xe7,
	0x60, 0x2b, 0xd8, 0xfe, 0x97, 0xe2, 0x6c, 0x1f, 0x84, 0xf9, 0x6c, 0x64, 0x51, 0x62, 0x52, 0x7b,
	0x42, 0x3c, 0x6a, 0x4d, 0x66, 0xed, 0xca, 0x6e, 0x76, 0x2f, 0xaf, 0x6f, 0xfa, 0xf4, 0x61, 0x48,
	0x66, 0x2a, 0x30, 0xfd, 0xcd, 0x4b, 0xc7, 0x9d, 0x58, 0xb4, 0x0d, 0x1c, 0x0c, 0x18, 0xe9, 0x90,
	0x53, 0xd0, 0x2e, 0x54, 0x47, 0xc4, 0xbb, 0x70, 0xed, 0x19, 0xb5, 0x9d, 0x69, 0xbb, 0xea, 0x4b,
	0x8b, 0x91, 0x18, 0xc4, 0xd8, 0xb9, 0xb0, 0xd8, 0xb7, 0x69, 0x8f, 0xda, 0x35, 0x1f, 0x22, 0x24,
	0xa9, 0xfc, 0xe5, 0x89, 0x18, 0xe6, 0xae, 0xdd, 0xae, 0xfb, 0x18, 0x21, 0xcd, 0x70, 0xed, 0xf5,
	0x61, 0xf1, 0x3d, 0xfc, 0xf7, 0x88, 0xd0, 0x9e, 0xe5, 0x85, 0xa1, 0xb1, 0x9a, 0x1c, 0x77, 0x5f,
	0x6a, 0x60, 0xa8, 0x47, 0x12, 0xbe, 0x0e, 0x48, 0x86, 0x3d, 0x12, 0xaf, 0x61, 0x67, 0x19, 0xfa,
	0xd6, 0x8b, 0x7b, 0x02, 0x30, 0x75, 0xcc, 0x1b, 0x9f, 0x8f, 0x63, 0x95, 0xf5, 0xca, 0xd4, 0x09,
	0x0e, 0xae, 0xb7, 0xe6, 0xcf, 0x2c, 0x08, 0x81, 0xb0, 0xee, 0x7b, 0x6b, 0x7a, 0x45, 0x06, 0x84,
	0x2e, 0x6b, 0x98, 0x5d, 0xd6, 0x10, 0x3d, 0x07, 0x34, 0xb3, 0x5c, 0x32, 0xa5, 0xa1, 0xe4, 0x98,
	0x25, 0x82, 0xbf, 0x13, 0x68, 0xc0, 0xb8, 0x45, 0xd8, 0xb0, 0x29, 0x99, 0x84, 0x69, 0x5f, 0x0b,
	0x43, 0x56, 0xa5, 0x64, 0xa2, 0xfb, 0x5b, 0x4c, 0xe4, 0xc5, 0x98, 0x58, 0x53, 0xd3, 0x1b, 0x5b,
	0xd4, 0x0f, 0xa5, 0xb2, 0x0e, 0x9c, 0x34, 0x60, 0x14, 0xb4, 0x03, 0x45, 0x97, 0x4c, 0x9c, 0x1b,
	0xd2, 0xde, 0xd8, 0xcd, 0xef, 0x55, 0xf4, 0x60, 0x85, 0xf6, 0xa2, 0xa2, 0x52, 0xe4, 0xe8, 0x02,
	0x5e, 0xf8, 0x2e, 0xf9, 0x08, 0x0f, 0xa1, 0x1e, 0x5a, 0xea, 0x4c, 0x26, 0x36, 0x5d, 0x54, 0xa9,
	0x6c, 0xbc, 0x4a, 0x7d, 0x0a, 0xe5, 0xc0, 0x52, 0xf6, 0x38, 0xe6, 0x79, 0x23, 0xb5, 0xec, 0x21,
	0x3d, 0x62, 0x61, 0xa8, 0x3e, 0x5c, 0x78, 0xff, 0xeb, 0x51, 0x4b, 0xeb, 0x51, 0xdf, 0x41, 0x23,
	0x44, 0x0d, 0xae, 0x7e, 0x1f, 0x84, 0xf0, 0x4e, 0x02, 0x9f, 0x7b, 0xed, 0xec, 0x6e, 0x7e, 0xaf,
	0xa6, 0x6f, 0x8e, 0x12, 0xc1, 0xe2, 0xad, 0xbf, 0xf4, 0x3a, 0x54, 0x07, 0xd4, 0x0a, 0x35, 0x16,
	0x55, 0xa8, 0xf9, 0xcb, 0x40, 0x54, 0x1b, 0x4a, 0x61, 0x40, 0xf9, 0x36, 0x84, 0xcb, 0xf5, 0xc8,
	0x03, 0xd8, 0x36, 0x78, 0x5e, 0x2f, 0x55, 0xba, 0xd5, 0xc0, 0x5d, 0x6e, 0xd3, 0xef, 0x28, 0x63,
	0xbf, 0xe6, 0xa0, 0x1c, 0x0a, 0x42, 0x4f, 0xa1, 0x70, 0xe1, 0x8c, 0x7c, 0xef, 0x36, 0x0e, 0xaa,
	0x98, 0x69, 0x3e, 0xf7, 0xba, 0xce, 0x88, 0xe8, 0x7c, 0xe3, 0x8e, 0xee, 0x83, 0x3d, 0x5b, 0xf3,
	0xf3, 0x28, 0x33, 0xf3, 0xc1, 0xb3, 0xe5, 0x93, 0x0c, 0xbf, 0x31, 0x0d, 0x19, 0xe2, 0x05, 0x2d,
	0xa0, 0xf1, 0x82, 0xf6, 0x04, 0xe0, 0xd2, 0x26, 0xe3, 0x91, 0xcf, 0xb0, 0xc1, 0x19, 0x2a, 0x9c,
	0xc2, 0xb7, 0x63, 0x0d, 0x4e, 0x91, 0x87, 0x69, 0xd4, 0x58, 0x2d, 0x17, 0xcb, 0xd2, 0xda, 0xa6,
	0xb7, 0xec, 0x97, 0xaf, 0x64, 0xe5, 0x98, 0x10, 0xfa, 0xde, 0x09, 0xa4, 0x57, 0x7c, 0x06, 0x9f,
	0xc4, 0x10, 0xc4, 0x17, 0x50, 0x57, 0x26, 0x33, 0xfa, 0x63, 0x74, 0x95, 0xeb, 0x2e, 0xec, 0xe3,
	0xbf, 0x72, 0x00, 0x0b, 0x17, 0xa2, 0x22, 0xe4, 0xfa, 0xaf, 0x85, 0x0c, 0xaa, 0x43, 0xa5, 0x2b,
	0x69, 0x5d, 0xa5, 0xd7, 0x53, 0x64, 0x21, 0x8b, 0xaa, 0x50, 0x32, 0xb4, 0xd7, 0x5a, 0xff, 0x5b,
	0x4d, 0xc8, 0xa1, 0x6d, 0x10, 0x54, 0xed, 0x4c, 0xea, 0xa9, 0xb2, 0x29, 0xe9, 0x47, 0xc6, 0x89,
	0xa2, 0x0d, 0x85, 0x3c, 0x6a, 0x41, 0x53, 0x56, 0x24, 0xb9, 0xa7, 0x6a, 0x8a, 0xa9, 0xbc, 0xe9,
	0x2a, 0x8a, 0xac, 0xc8, 0x42, 0x81, 0x01, 0x69, 0xfd, 0xa1, 0x79, 0xd8, 0x37, 0x34, 0x59, 0xd8,
	0x40, 0x08, 0x1a, 0x52, 0x4f, 0x57, 0x24, 0xf9, 0xad, 0xa9, 0xbc, 0x51, 0x07, 0xc3, 0x81, 0x50,
	0x64, 0x27, 0x4f, 0x15, 0xfd, 0x44, 0x1d, 0x0c, 0xd4, 0xbe, 0x66, 0xca, 0x8a, 0xa6, 0x2a, 0xb2,
	0x50, 0x42, 0x5b, 0xb0, 0x69, 0x68, 0x92, 0x31, 0x3c, 0x56, 0xb4, 0xa1, 0xda, 0x95, 0x86, 0x8a,
	0x2c, 0x08, 0x68, 0x07, 0x90, 0xae, 0x0c, 0xfa, 0x86, 0xde, 0x65, 0x52, 0x8e, 0x25, 0x63, 0xc0,
	0xe8, 0x65, 0xf4, 0x08, 0xb6, 0x0e, 0x25, 0xb5, 0xa7, 0xc8, 0xe6, 0xa9, 0xae, 0x74, 0xfb, 0x9a,
	0xac, 0x0e, 0xd5, 0xbe, 0x26, 0x54, 0x98, 0xe6, 0xd2, 0xcb, 0xbe, 0xce, 0xb8, 0x00, 0x09, 0x50,
	0xeb, 0x1b, 0x43, 0xb3, 0x7f, 0x68, 0xea, 0x92, 0x76, 0xa4, 0x08, 0x55, 0xd4, 0x84, 0xba, 0xa1,
	0xa9, 0x27, 0xa7, 0x3d, 0x85, 0x99, 0xa1, 0xc8, 0x42, 0x0d, 0xd5, 0xa0, 0xac, 0x6a, 0x43, 0x45,
	0xd7, 0xa4, 0x9e, 0x50, 0x47, 0x9b, 0x50, 0x35, 0x34, 0xe9, 0x4c, 0x52, 0x7b, 0xd2, 0xcb, 0x9e,
	0x22, 0x34, 0x98, 0x41, 0xb2, 0x34, 0x94, 0xcc, 0x5e, 0x7f, 0x30, 0x10, 0x36, 0x19, 0xf7, 0x4b,
	0x49, 0x36, 0x35, 0xe9, 0x44, 0x11, 0x46, 0xa8, 0x01, 0xc0, 0xbe, 0xcc, 0xa1, 0xf4, 0x5a, 0xd1,
	0x04, 0xc2, 0x5c, 0x75, 0xa6, 0xe8, 0xdc, 0xae, 0x13, 0x75, 0x70, 0x22, 0x0d, 0xbb, 0xc7, 0xc2,
	0xe5, 0xc1, 0x1f, 0x25, 0x28, 0x75, 0x2d, 0x6a, 0x8d, 0x9d, 0x2b, 0xf4, 0x35, 0xd4, 0x13, 0x93,
	0x2d, 0x6a, 0xe1, 0xb4, 0x49, 0xb7, 0xb3, 0x8d, 0x53, 0x06, 0x50, 0x31, 0x83, 0xbe, 0x00, 0x58,
	0x8c, 0xb0, 0x08, 0xe1, 0x95, 0x79, 0xf6, 0xd6, 0x93, 0x91, 0xe4, 0xa0, 0x63, 0x8a, 0x24, 0x27,
	0x3b, 0xdc, 0x4e, 0xd4, 0xa5, 0xa5, 0x4a, 0x0e, 0x0f, 0x73, 0xc9, 0xf7, 0x3c, 0xd9, 0x83, 0xe6,
	0x4a, 0xa3, 0x86, 0x1e, 0xe3, 0xdb, 0xda, 0xcd, 0x4e, 0x07, 0xdf, 0xda, 0xd7, 0x89, 0x19, 0x74,
	0x00, 0x95, 0x68, 0x7a, 0x46, 0x4d, 0xbc, 0x3c, 0x49, 0x77, 0x04, 0xbc, 0x34, 0xa5, 0x8a, 0x19,
	0xd6, 0x89, 0xfa, 0x13, 0x30, 0x6a, 0xe0, 0xc4, 0x28, 0x9c, 0xca, 0xfd, 0x25, 0x2f, 0x97, 0xe1,
	0x24, 0x89, 0xb6, 0xf0, 0xea, 0x5c, 0xd9, 0xd9, 0xc2, 0xab, 0x03, 0x9e, 0x98, 0x41, 0x2f, 0xa0,
	0x12, 0x8d, 0x63, 0xa8, 0x89, 0x97, 0x47, 0xb3, 0x4e, 0x03, 0x27, 0xf2, 0x95, 0x9b, 0x03, 0x8b,
	0x19, 0x0b, 0x21, 0xbc, 0x32, 0x70, 0xa5, 0x9c, 0xf9, 0x8a, 0xbf, 0x16, 0xb1, 0xe1, 0x09, 0xed,
	0xe0, 0xd4, 0x69, 0x2a, 0xe5, 0x6c, 0x14, 0x06, 0x41, 0x01, 0x8e, 0xc2, 0x20, 0x59, 0xc1, 0x3b,
	0xdb, 0x38, 0xa5, 0x93, 0x8c, 0xc2, 0x20, 0x3c, 0xcc, 0xc3, 0xe0, 0xde, 0x27, 0xeb, 0x89, 0xb7,
	0x02, 0xb5, 0x70, 0xda, 0xdb, 0x91, 0xa2, 0xf3, 0x37, 0xd0, 0x4a, 0x6d, 0xc1, 0xd0, 0x13, 0x7c,
	0x57, 0x6b, 0xd6, 0x79, 0x84, 0xd3, 0xfb, 0x2a, 0x31, 0x83, 0x3e, 0x81, 0x62, 0xd0, 0x15, 0x34,
	0x70, 0xe2, 0x3d, 0xef, 0x6c, 0xe2, 0xe4, 0x4b, 0x2c, 0x66, 0xd0, 0x33, 0x28, 0xb0, 0x9a, 0x89,
	0x6a, 0x38, 0xf6, 0x8c, 0x76, 0xea, 0x38, 0xfe, 0x8a, 0x8a, 0x99, 0xf3, 0x22, 0xff, 0x79, 0xf5,
	0xf9, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x17, 0x86, 0x65, 0xd7, 0x12, 0x00, 0x00,
}
