// Code generated by protoc-gen-go.
// source: mlp_api.proto
// DO NOT EDIT!

/*
Package mlp_api is a generated protocol buffer package.

It is generated from these files:
	mlp_api.proto

It has these top-level messages:
	CreateProjectRequest
	CreateProjectResponse
	CreateDatasetResponse
	StatRequest
	StatResponse
	CreateJobRequest
	CreateJobResponse
	LookupProjectRequest
	LookupProjectResponse
	ApiResponse
	CreateDatasetRequest
	UpdateDatasetRequest
	ApiError
*/
package mlp_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import vo "mlp/catalog/vo"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	// codes in gRPC
	StatusCode_OK StatusCode = 0
	// The operation was cancelled, typically by the caller.
	StatusCode_CANCELLED StatusCode = 1
	// Unknown error.  For example, this error may be returned when
	// a `Status` value received from another address space belongs to
	// an error space that is not known in this address space.  Also
	// errors raised by APIs that do not return enough error information
	// may be converted to this error.
	StatusCode_UNKNOWN StatusCode = 2
	// The client specified an invalid argument.  Note that this differs
	// from `FAILED_PRECONDITION`.  `INVALID_ARGUMENT` indicates arguments
	// that are problematic regardless of the state of the system
	// (e.g., a malformed file name).
	//
	// HTTP Mapping: 400 Bad Request
	StatusCode_INVALID_ARGUMENT StatusCode = 3
	// The deadline expired before the operation could complete. For operations
	// that change the state of the system, this error may be returned
	// even if the operation has completed successfully.  For example, a
	// successful response from a server could have been delayed long
	// enough for the deadline to expire.
	StatusCode_DEADLINE_EXCEEDED StatusCode = 4
	StatusCode_NOT_FOUND         StatusCode = 5
	// The entity that a client attempted to create (e.g., file or directory)
	// already exists.
	StatusCode_ALREADY_EXISTS StatusCode = 6
	// The caller does not have permission to execute the specified
	// operation. `PERMISSION_DENIED` must not be used for rejections
	// caused by exhausting some resource (use `RESOURCE_EXHAUSTED`
	// instead for those errors). `PERMISSION_DENIED` must not be
	// used if the caller can not be identified (use `UNAUTHENTICATED`
	// instead for those errors). This error code does not imply the
	// request is valid or the requested entity exists or satisfies
	// other pre-conditions.
	StatusCode_PERMISSION_DENIED StatusCode = 7
	// The request does not have valid authentication credentials for the
	// operation.
	StatusCode_UNAUTHENTICATED StatusCode = 16
	// Some resource has been exhausted, perhaps a per-user quota, or
	// perhaps the entire file system is out of space.
	StatusCode_RESOURCE_EXHAUSTED StatusCode = 8
	// The operation was rejected because the system is not in a state
	// required for the operation's execution.  For example, the directory
	// to be deleted is non-empty, an rmdir operation is applied to
	// a non-directory, etc.
	//
	// Service implementors can use the following guidelines to decide
	// between `FAILED_PRECONDITION`, `ABORTED`, and `UNAVAILABLE`:
	//  (a) Use `UNAVAILABLE` if the client can retry just the failing call.
	//  (b) Use `ABORTED` if the client should retry at a higher level
	//      (e.g., when a client-specified test-and-set fails, indicating the
	//      client should restart a read-modify-write sequence).
	//  (c) Use `FAILED_PRECONDITION` if the client should not retry until
	//      the system state has been explicitly fixed.  E.g., if an "rmdir"
	//      fails because the directory is non-empty, `FAILED_PRECONDITION`
	//      should be returned since the client should not retry unless
	//      the files are deleted from the directory.
	//
	// HTTP Mapping: 400 Bad Request
	StatusCode_FAILED_PRECONDITION StatusCode = 9
	// The operation was aborted, typically due to a concurrency issue such as
	// a sequencer check failure or transaction abort.
	StatusCode_ABORTED StatusCode = 10
	// The operation was attempted past the valid range.  E.g., seeking or
	// reading past end-of-file.
	StatusCode_OUT_OF_RANGE StatusCode = 11
	// The operation is not implemented or is not supported/enabled in this
	// service.
	//
	// HTTP Mapping: 501 Not Implemented
	StatusCode_UNIMPLEMENTED StatusCode = 12
	StatusCode_INTERNAL      StatusCode = 13
	// The service is currently unavailable.  This is most likely a
	// transient condition, which can be corrected by retrying with
	// a backoff.
	StatusCode_UNAVAILABLE StatusCode = 14
	// Unrecoverable data loss or corruption.
	StatusCode_DATA_LOSS StatusCode = 15
	// Bad entity name was supplied
	StatusCode_BAD_NAME   StatusCode = 100
	StatusCode_NAME_TAKEN StatusCode = 101
)

var StatusCode_name = map[int32]string{
	0:   "OK",
	1:   "CANCELLED",
	2:   "UNKNOWN",
	3:   "INVALID_ARGUMENT",
	4:   "DEADLINE_EXCEEDED",
	5:   "NOT_FOUND",
	6:   "ALREADY_EXISTS",
	7:   "PERMISSION_DENIED",
	16:  "UNAUTHENTICATED",
	8:   "RESOURCE_EXHAUSTED",
	9:   "FAILED_PRECONDITION",
	10:  "ABORTED",
	11:  "OUT_OF_RANGE",
	12:  "UNIMPLEMENTED",
	13:  "INTERNAL",
	14:  "UNAVAILABLE",
	15:  "DATA_LOSS",
	100: "BAD_NAME",
	101: "NAME_TAKEN",
}
var StatusCode_value = map[string]int32{
	"OK":                  0,
	"CANCELLED":           1,
	"UNKNOWN":             2,
	"INVALID_ARGUMENT":    3,
	"DEADLINE_EXCEEDED":   4,
	"NOT_FOUND":           5,
	"ALREADY_EXISTS":      6,
	"PERMISSION_DENIED":   7,
	"UNAUTHENTICATED":     16,
	"RESOURCE_EXHAUSTED":  8,
	"FAILED_PRECONDITION": 9,
	"ABORTED":             10,
	"OUT_OF_RANGE":        11,
	"UNIMPLEMENTED":       12,
	"INTERNAL":            13,
	"UNAVAILABLE":         14,
	"DATA_LOSS":           15,
	"BAD_NAME":            100,
	"NAME_TAKEN":          101,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateProjectRequest struct {
	Name string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Meta *vo.ProjectMetadataDelta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *CreateProjectRequest) Reset()                    { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()               {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateProjectRequest) GetMeta() *vo.ProjectMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type CreateProjectResponse struct {
	Error *ApiError `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Uid   []byte    `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (m *CreateProjectResponse) Reset()                    { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()               {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateProjectResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateDatasetResponse struct {
	Error *ApiError `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Uid   []byte    `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (m *CreateDatasetResponse) Reset()                    { *m = CreateDatasetResponse{} }
func (m *CreateDatasetResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDatasetResponse) ProtoMessage()               {}
func (*CreateDatasetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateDatasetResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type StatRequest struct {
}

func (m *StatRequest) Reset()                    { *m = StatRequest{} }
func (m *StatRequest) String() string            { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()               {}
func (*StatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type StatResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *StatResponse) Reset()                    { *m = StatResponse{} }
func (m *StatResponse) String() string            { return proto.CompactTextString(m) }
func (*StatResponse) ProtoMessage()               {}
func (*StatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type CreateJobRequest struct {
	ProjectUid []byte               `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name       string               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Meta       *vo.JobMetadataDelta `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
}

func (m *CreateJobRequest) Reset()                    { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()               {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateJobRequest) GetMeta() *vo.JobMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type CreateJobResponse struct {
	Error *ApiError `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Uid   []byte    `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (m *CreateJobResponse) Reset()                    { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()               {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateJobResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type LookupProjectRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *LookupProjectRequest) Reset()                    { *m = LookupProjectRequest{} }
func (m *LookupProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*LookupProjectRequest) ProtoMessage()               {}
func (*LookupProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type LookupProjectResponse struct {
	Error *ApiError `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Uid   []byte    `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (m *LookupProjectResponse) Reset()                    { *m = LookupProjectResponse{} }
func (m *LookupProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupProjectResponse) ProtoMessage()               {}
func (*LookupProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LookupProjectResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type ApiResponse struct {
	Error *ApiError `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ApiResponse) Reset()                    { *m = ApiResponse{} }
func (m *ApiResponse) String() string            { return proto.CompactTextString(m) }
func (*ApiResponse) ProtoMessage()               {}
func (*ApiResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ApiResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateDatasetRequest struct {
	ProjectUid []byte                   `protobuf:"bytes,1,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name       string                   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Meta       *vo.DatasetMetadataDelta `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
}

func (m *CreateDatasetRequest) Reset()                    { *m = CreateDatasetRequest{} }
func (m *CreateDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDatasetRequest) ProtoMessage()               {}
func (*CreateDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateDatasetRequest) GetMeta() *vo.DatasetMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type UpdateDatasetRequest struct {
	// option 1
	Uid  []byte                   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Meta *vo.DatasetMetadataDelta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *UpdateDatasetRequest) Reset()                    { *m = UpdateDatasetRequest{} }
func (m *UpdateDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDatasetRequest) ProtoMessage()               {}
func (*UpdateDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UpdateDatasetRequest) GetMeta() *vo.DatasetMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ApiError struct {
	Code    StatusCode `protobuf:"varint,1,opt,name=code,enum=StatusCode" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// For API matching and tests
	SubjectUid  []byte   `protobuf:"bytes,3,opt,name=subject_uid,json=subjectUid,proto3" json:"subject_uid,omitempty"`
	SubjectName string   `protobuf:"bytes,4,opt,name=subject_name,json=subjectName" json:"subject_name,omitempty"`
	FieldName   string   `protobuf:"bytes,5,opt,name=field_name,json=fieldName" json:"field_name,omitempty"`
	Details     []string `protobuf:"bytes,6,rep,name=details" json:"details,omitempty"`
}

func (m *ApiError) Reset()                    { *m = ApiError{} }
func (m *ApiError) String() string            { return proto.CompactTextString(m) }
func (*ApiError) ProtoMessage()               {}
func (*ApiError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*CreateProjectRequest)(nil), "CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "CreateProjectResponse")
	proto.RegisterType((*CreateDatasetResponse)(nil), "CreateDatasetResponse")
	proto.RegisterType((*StatRequest)(nil), "StatRequest")
	proto.RegisterType((*StatResponse)(nil), "StatResponse")
	proto.RegisterType((*CreateJobRequest)(nil), "CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "CreateJobResponse")
	proto.RegisterType((*LookupProjectRequest)(nil), "LookupProjectRequest")
	proto.RegisterType((*LookupProjectResponse)(nil), "LookupProjectResponse")
	proto.RegisterType((*ApiResponse)(nil), "ApiResponse")
	proto.RegisterType((*CreateDatasetRequest)(nil), "CreateDatasetRequest")
	proto.RegisterType((*UpdateDatasetRequest)(nil), "UpdateDatasetRequest")
	proto.RegisterType((*ApiError)(nil), "ApiError")
	proto.RegisterEnum("StatusCode", StatusCode_name, StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Catalog service

type CatalogClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*CreateDatasetResponse, error)
	UpdateDataset(ctx context.Context, in *UpdateDatasetRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	LookupProject(ctx context.Context, in *LookupProjectRequest, opts ...grpc.CallOption) (*LookupProjectResponse, error)
}

type catalogClient struct {
	cc *grpc.ClientConn
}

func NewCatalogClient(cc *grpc.ClientConn) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := grpc.Invoke(ctx, "/Catalog/CreateProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*CreateDatasetResponse, error) {
	out := new(CreateDatasetResponse)
	err := grpc.Invoke(ctx, "/Catalog/CreateDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) UpdateDataset(ctx context.Context, in *UpdateDatasetRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	out := new(ApiResponse)
	err := grpc.Invoke(ctx, "/Catalog/UpdateDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := grpc.Invoke(ctx, "/Catalog/CreateJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	out := new(StatResponse)
	err := grpc.Invoke(ctx, "/Catalog/Stat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) LookupProject(ctx context.Context, in *LookupProjectRequest, opts ...grpc.CallOption) (*LookupProjectResponse, error) {
	out := new(LookupProjectResponse)
	err := grpc.Invoke(ctx, "/Catalog/LookupProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Catalog service

type CatalogServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	CreateDataset(context.Context, *CreateDatasetRequest) (*CreateDatasetResponse, error)
	UpdateDataset(context.Context, *UpdateDatasetRequest) (*ApiResponse, error)
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	LookupProject(context.Context, *LookupProjectRequest) (*LookupProjectResponse, error)
}

func RegisterCatalogServer(s *grpc.Server, srv CatalogServer) {
	s.RegisterService(&_Catalog_serviceDesc, srv)
}

func _Catalog_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_CreateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CreateDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateDataset(ctx, req.(*CreateDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_UpdateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).UpdateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/UpdateDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).UpdateDataset(ctx, req.(*UpdateDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_LookupProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).LookupProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/LookupProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).LookupProject(ctx, req.(*LookupProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Catalog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _Catalog_CreateProject_Handler,
		},
		{
			MethodName: "CreateDataset",
			Handler:    _Catalog_CreateDataset_Handler,
		},
		{
			MethodName: "UpdateDataset",
			Handler:    _Catalog_UpdateDataset_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _Catalog_CreateJob_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Catalog_Stat_Handler,
		},
		{
			MethodName: "LookupProject",
			Handler:    _Catalog_LookupProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("mlp_api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 796 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6f, 0xdb, 0x36,
	0x14, 0xf5, 0x57, 0xe2, 0xf8, 0x4a, 0x4a, 0x68, 0x36, 0xce, 0x0c, 0x03, 0x43, 0x32, 0x01, 0x03,
	0xd2, 0x3e, 0xf0, 0x21, 0x1b, 0xf6, 0x3c, 0x46, 0x64, 0x5a, 0x25, 0x32, 0x15, 0xe8, 0xa3, 0xeb,
	0x9e, 0x04, 0xa5, 0xe2, 0x0a, 0x6d, 0x4e, 0xa4, 0x59, 0x72, 0x7e, 0xe0, 0xfe, 0xc6, 0x5e, 0xf7,
	0x43, 0x06, 0xea, 0xc3, 0xb1, 0x13, 0x63, 0x2b, 0xda, 0x37, 0xf2, 0xea, 0xf2, 0xdc, 0x7b, 0x0e,
	0x2f, 0x8f, 0xc0, 0xb8, 0x5f, 0xe4, 0x51, 0x9c, 0xa7, 0x24, 0x5f, 0x66, 0x65, 0x36, 0x3b, 0x78,
	0xcc, 0xea, 0x95, 0x19, 0xc2, 0xb1, 0xb5, 0x94, 0x71, 0x29, 0x6f, 0x97, 0xd9, 0xef, 0xf2, 0x63,
	0xe9, 0xc9, 0x3f, 0x57, 0xb2, 0x28, 0x31, 0x86, 0xc1, 0x43, 0x7c, 0x2f, 0xa7, 0xdd, 0xb3, 0xee,
	0xf9, 0xc8, 0xab, 0xd6, 0xf8, 0x35, 0x0c, 0xee, 0x65, 0x19, 0x4f, 0x7b, 0x67, 0xdd, 0x73, 0xed,
	0x62, 0x42, 0x9a, 0x23, 0x73, 0x59, 0xc6, 0x49, 0x5c, 0xc6, 0x4c, 0x2e, 0xca, 0xd8, 0xab, 0x52,
	0xcc, 0x6b, 0x98, 0x3c, 0x83, 0x2d, 0xf2, 0xec, 0xa1, 0x90, 0xf8, 0x14, 0xf6, 0xe4, 0x72, 0x99,
	0x2d, 0x2b, 0x60, 0xed, 0x62, 0x44, 0x68, 0x9e, 0x72, 0x15, 0xf0, 0xea, 0x38, 0x46, 0xd0, 0x5f,
	0xa5, 0x49, 0x55, 0x43, 0xf7, 0xd4, 0xf2, 0x09, 0x8b, 0xc5, 0x65, 0x5c, 0xc8, 0xaf, 0xc2, 0x32,
	0x40, 0xf3, 0xcb, 0xb8, 0x65, 0x69, 0x9e, 0x83, 0x5e, 0x6f, 0x1b, 0xc4, 0x29, 0x0c, 0x1f, 0xe5,
	0xb2, 0x48, 0xb3, 0x87, 0x86, 0x78, 0xbb, 0x35, 0x1f, 0x00, 0xd5, 0x4d, 0x5c, 0x67, 0x77, 0xad,
	0x46, 0xa7, 0xa0, 0xe5, 0x35, 0xbd, 0x48, 0x95, 0xe9, 0x56, 0x65, 0xa0, 0x09, 0x85, 0x69, 0xb2,
	0x16, 0xb1, 0xb7, 0x21, 0xe2, 0xf7, 0x8d, 0x88, 0xfd, 0xaa, 0xe7, 0x31, 0xb9, 0xce, 0xee, 0x76,
	0x09, 0x78, 0x05, 0xe3, 0x8d, 0x7a, 0x5f, 0x4e, 0xf8, 0x0d, 0x1c, 0x3b, 0x59, 0xf6, 0xc7, 0x2a,
	0xff, 0xff, 0xfb, 0x55, 0x42, 0x3f, 0xcb, 0xfd, 0xf2, 0xba, 0x04, 0x34, 0x9a, 0xa7, 0x9f, 0x8d,
	0x60, 0x3e, 0xb6, 0x73, 0xb8, 0xbe, 0xe4, 0xaf, 0xd0, 0xf8, 0xf5, 0x96, 0xc6, 0x13, 0xd2, 0x60,
	0xee, 0xd2, 0xd9, 0x87, 0xe3, 0x30, 0x4f, 0x5e, 0xd6, 0x6d, 0x18, 0x75, 0xd7, 0x8c, 0x5e, 0x4c,
	0xff, 0x7f, 0x80, 0xfe, 0xd5, 0x85, 0x83, 0x96, 0x20, 0x3e, 0x85, 0xc1, 0xc7, 0x2c, 0xa9, 0x95,
	0x3e, 0xbc, 0xd0, 0x88, 0x1a, 0xb8, 0x55, 0x61, 0x65, 0x89, 0xf4, 0xaa, 0x0f, 0x6a, 0xe8, 0xee,
	0x65, 0x51, 0xc4, 0x9f, 0x5a, 0x12, 0xed, 0x56, 0x91, 0x2f, 0x56, 0x77, 0x6b, 0xf2, 0xfd, 0x9a,
	0x7c, 0x13, 0x52, 0xe4, 0xbf, 0x03, 0xbd, 0x4d, 0xa8, 0x44, 0x18, 0x54, 0xe7, 0xdb, 0x43, 0x42,
	0x69, 0xf1, 0x2d, 0xc0, 0x6f, 0xa9, 0x5c, 0x24, 0x75, 0xc2, 0x5e, 0x95, 0x30, 0xaa, 0x22, 0xd5,
	0xe7, 0x29, 0x0c, 0x13, 0x59, 0xc6, 0xe9, 0xa2, 0x98, 0xee, 0x9f, 0xf5, 0x55, 0xf1, 0x66, 0xfb,
	0xe6, 0xef, 0x1e, 0xc0, 0x53, 0xaf, 0x78, 0x1f, 0x7a, 0xee, 0x0d, 0xea, 0x60, 0x03, 0x46, 0x16,
	0x15, 0x16, 0x77, 0x1c, 0xce, 0x50, 0x17, 0x6b, 0x30, 0x0c, 0xc5, 0x8d, 0x70, 0x7f, 0x11, 0xa8,
	0x87, 0x8f, 0x01, 0xd9, 0xe2, 0x3d, 0x75, 0x6c, 0x16, 0x51, 0xef, 0x6d, 0x38, 0xe7, 0x22, 0x40,
	0x7d, 0x3c, 0x81, 0x31, 0xe3, 0x94, 0x39, 0xb6, 0xe0, 0x11, 0xff, 0x60, 0x71, 0xce, 0x38, 0x43,
	0x03, 0x05, 0x24, 0xdc, 0x20, 0xba, 0x72, 0x43, 0xc1, 0xd0, 0x1e, 0xc6, 0x70, 0x48, 0x1d, 0x8f,
	0x53, 0xf6, 0x6b, 0xc4, 0x3f, 0xd8, 0x7e, 0xe0, 0xa3, 0x7d, 0x75, 0xf2, 0x96, 0x7b, 0x73, 0xdb,
	0xf7, 0x6d, 0x57, 0x44, 0x8c, 0x0b, 0x9b, 0x33, 0x34, 0xc4, 0xaf, 0xe0, 0x28, 0x14, 0x34, 0x0c,
	0xde, 0x71, 0x11, 0xd8, 0x16, 0x0d, 0x38, 0x43, 0x08, 0x9f, 0x00, 0xf6, 0xb8, 0xef, 0x86, 0x9e,
	0xa5, 0xaa, 0xbc, 0xa3, 0xa1, 0xaf, 0xe2, 0x07, 0xf8, 0x1b, 0x78, 0x75, 0x45, 0x6d, 0x87, 0xb3,
	0xe8, 0xd6, 0xe3, 0x96, 0x2b, 0x98, 0x1d, 0xd8, 0xae, 0x40, 0x23, 0xd5, 0x39, 0xbd, 0x74, 0x3d,
	0x95, 0x05, 0x18, 0x81, 0xee, 0x86, 0x41, 0xe4, 0x5e, 0x45, 0x1e, 0x15, 0x6f, 0x39, 0xd2, 0xf0,
	0x18, 0x8c, 0x50, 0xd8, 0xf3, 0x5b, 0x87, 0x2b, 0x1a, 0x9c, 0x21, 0x1d, 0xeb, 0x70, 0x60, 0x8b,
	0x80, 0x7b, 0x82, 0x3a, 0xc8, 0xc0, 0x47, 0xa0, 0x85, 0x82, 0xbe, 0xa7, 0xb6, 0x43, 0x2f, 0x1d,
	0x8e, 0x0e, 0x15, 0x21, 0x46, 0x03, 0x1a, 0x39, 0xae, 0xef, 0xa3, 0x23, 0x95, 0x7d, 0x49, 0x59,
	0x24, 0xe8, 0x9c, 0xa3, 0x04, 0x1f, 0x02, 0xa8, 0x55, 0x14, 0xd0, 0x1b, 0x2e, 0x90, 0xbc, 0xf8,
	0xa7, 0x07, 0x43, 0x2b, 0x2e, 0xe3, 0x45, 0xf6, 0x09, 0xff, 0x0c, 0xc6, 0x96, 0x59, 0xe2, 0x09,
	0xd9, 0xe5, 0xc9, 0xb3, 0x13, 0xb2, 0xd3, 0x53, 0xcd, 0xce, 0x13, 0x42, 0x33, 0x94, 0x6b, 0x84,
	0xed, 0xa9, 0x5e, 0x23, 0x3c, 0x73, 0x52, 0xb3, 0x83, 0x7f, 0x02, 0x63, 0xeb, 0x1d, 0xe0, 0x09,
	0xd9, 0xf5, 0x2e, 0x66, 0x3a, 0xd9, 0x78, 0xd6, 0x66, 0x07, 0xff, 0x08, 0xa3, 0xb5, 0x4f, 0xe1,
	0x31, 0x79, 0xee, 0x91, 0x33, 0x4c, 0x5e, 0xd8, 0x98, 0xd9, 0x51, 0x26, 0xa8, 0x46, 0x0b, 0xeb,
	0x64, 0xc3, 0x8d, 0x67, 0x06, 0xd9, 0x34, 0xe3, 0x9a, 0xd6, 0x96, 0x21, 0xe1, 0x09, 0xd9, 0x65,
	0x66, 0xb3, 0x13, 0xb2, 0xd3, 0xb7, 0xcc, 0xce, 0xdd, 0x7e, 0xf5, 0x97, 0xfb, 0xe1, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xab, 0x32, 0x5c, 0xed, 0x00, 0x07, 0x00, 0x00,
}
