// Code generated by protoc-gen-go.
// source: mlp_api.proto
// DO NOT EDIT!

/*
Package mlp_api is a generated protocol buffer package.

It is generated from these files:
	mlp_api.proto

It has these top-level messages:
	CreateProjectRequest
	GetProjectRequest
	ProjectInfo
	ProjectInfoResponse
	GetDatasetRequest
	CreateDatasetRequest
	UpdateDatasetRequest
	ListProjectsRequest
	ListProjectsResponse
	ListDatasetsRequest
	ListDatasetsResponse
	DatasetInfo
	DatasetInfoResponse
	StatRequest
	StatResponse
	ResetRequest
	ApiError
	EmptyResponse
*/
package mlp_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import vo "mlp/catalog/vo"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	// codes in gRPC
	StatusCode_OK StatusCode = 0
	// The operation was cancelled, typically by the caller.
	StatusCode_CANCELLED StatusCode = 1
	// Unknown error.  For example, this error may be returned when
	// a `Status` value received from another address space belongs to
	// an error space that is not known in this address space.  Also
	// errors raised by APIs that do not return enough error information
	// may be converted to this error.
	StatusCode_UNKNOWN StatusCode = 2
	// The client specified an invalid argument.  Note that this differs
	// from `FAILED_PRECONDITION`.  `INVALID_ARGUMENT` indicates arguments
	// that are problematic regardless of the state of the system
	// (e.g., a malformed file name).
	//
	// HTTP Mapping: 400 Bad Request
	StatusCode_INVALID_ARGUMENT StatusCode = 3
	// The deadline expired before the operation could complete. For operations
	// that change the state of the system, this error may be returned
	// even if the operation has completed successfully.  For example, a
	// successful response from a server could have been delayed long
	// enough for the deadline to expire.
	StatusCode_DEADLINE_EXCEEDED StatusCode = 4
	StatusCode_NOT_FOUND         StatusCode = 5
	// The entity that a client attempted to create (e.g., file or directory)
	// already exists.
	StatusCode_ALREADY_EXISTS StatusCode = 6
	// The caller does not have permission to execute the specified
	// operation. `PERMISSION_DENIED` must not be used for rejections
	// caused by exhausting some resource (use `RESOURCE_EXHAUSTED`
	// instead for those errors). `PERMISSION_DENIED` must not be
	// used if the caller can not be identified (use `UNAUTHENTICATED`
	// instead for those errors). This error code does not imply the
	// request is valid or the requested entity exists or satisfies
	// other pre-conditions.
	StatusCode_PERMISSION_DENIED StatusCode = 7
	// The request does not have valid authentication credentials for the
	// operation.
	StatusCode_UNAUTHENTICATED StatusCode = 16
	// Some resource has been exhausted, perhaps a per-user quota, or
	// perhaps the entire file system is out of space.
	StatusCode_RESOURCE_EXHAUSTED StatusCode = 8
	// The operation was rejected because the system is not in a state
	// required for the operation's execution.  For example, the directory
	// to be deleted is non-empty, an rmdir operation is applied to
	// a non-directory, etc.
	//
	// System implementors can use the following guidelines to decide
	// between `FAILED_PRECONDITION`, `ABORTED`, and `UNAVAILABLE`:
	//  (a) Use `UNAVAILABLE` if the client can retry just the failing call.
	//  (b) Use `ABORTED` if the client should retry at a higher level
	//      (e.g., when a client-specified test-and-set fails, indicating the
	//      client should restart a read-modify-write sequence).
	//  (c) Use `FAILED_PRECONDITION` if the client should not retry until
	//      the system state has been explicitly fixed.  E.g., if an "rmdir"
	//      fails because the directory is non-empty, `FAILED_PRECONDITION`
	//      should be returned since the client should not retry unless
	//      the files are deleted from the directory.
	//
	// HTTP Mapping: 400 Bad Request
	StatusCode_FAILED_PRECONDITION StatusCode = 9
	// The operation was aborted, typically due to a concurrency issue such as
	// a sequencer check failure or transaction abort.
	StatusCode_ABORTED StatusCode = 10
	// The operation was attempted past the valid range.  E.g., seeking or
	// reading past end-of-file.
	StatusCode_OUT_OF_RANGE StatusCode = 11
	// The operation is not implemented or is not supported/enabled in this
	// service.
	//
	// HTTP Mapping: 501 Not Implemented
	StatusCode_UNIMPLEMENTED StatusCode = 12
	StatusCode_INTERNAL      StatusCode = 13
	// The service is currently unavailable.  This is most likely a
	// transient condition, which can be corrected by retrying with
	// a backoff.
	StatusCode_UNAVAILABLE StatusCode = 14
	// Unrecoverable data loss or corruption.
	StatusCode_DATA_LOSS StatusCode = 15
	// Bad entity name was supplied
	StatusCode_BAD_NAME         StatusCode = 100
	StatusCode_NAME_TAKEN       StatusCode = 101
	StatusCode_VERSION_MISMATCH StatusCode = 102
)

var StatusCode_name = map[int32]string{
	0:   "OK",
	1:   "CANCELLED",
	2:   "UNKNOWN",
	3:   "INVALID_ARGUMENT",
	4:   "DEADLINE_EXCEEDED",
	5:   "NOT_FOUND",
	6:   "ALREADY_EXISTS",
	7:   "PERMISSION_DENIED",
	16:  "UNAUTHENTICATED",
	8:   "RESOURCE_EXHAUSTED",
	9:   "FAILED_PRECONDITION",
	10:  "ABORTED",
	11:  "OUT_OF_RANGE",
	12:  "UNIMPLEMENTED",
	13:  "INTERNAL",
	14:  "UNAVAILABLE",
	15:  "DATA_LOSS",
	100: "BAD_NAME",
	101: "NAME_TAKEN",
	102: "VERSION_MISMATCH",
}
var StatusCode_value = map[string]int32{
	"OK":                  0,
	"CANCELLED":           1,
	"UNKNOWN":             2,
	"INVALID_ARGUMENT":    3,
	"DEADLINE_EXCEEDED":   4,
	"NOT_FOUND":           5,
	"ALREADY_EXISTS":      6,
	"PERMISSION_DENIED":   7,
	"UNAUTHENTICATED":     16,
	"RESOURCE_EXHAUSTED":  8,
	"FAILED_PRECONDITION": 9,
	"ABORTED":             10,
	"OUT_OF_RANGE":        11,
	"UNIMPLEMENTED":       12,
	"INTERNAL":            13,
	"UNAVAILABLE":         14,
	"DATA_LOSS":           15,
	"BAD_NAME":            100,
	"NAME_TAKEN":          101,
	"VERSION_MISMATCH":    102,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// PROJECT
type CreateProjectRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *CreateProjectRequest) Reset()                    { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()               {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetProjectRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *GetProjectRequest) Reset()                    { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()               {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ProjectInfo struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *ProjectInfo) Reset()                    { *m = ProjectInfo{} }
func (m *ProjectInfo) String() string            { return proto.CompactTextString(m) }
func (*ProjectInfo) ProtoMessage()               {}
func (*ProjectInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ProjectInfoResponse struct {
	ProjectId string    `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Error     *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *ProjectInfoResponse) Reset()                    { *m = ProjectInfoResponse{} }
func (m *ProjectInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*ProjectInfoResponse) ProtoMessage()               {}
func (*ProjectInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProjectInfoResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

// -> DatasetResponse
type GetDatasetRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DatasetId string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
}

func (m *GetDatasetRequest) Reset()                    { *m = GetDatasetRequest{} }
func (m *GetDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDatasetRequest) ProtoMessage()               {}
func (*GetDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type CreateDatasetRequest struct {
	ProjectId string                   `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DatasetId string                   `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	Meta      *vo.DatasetMetadataDelta `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
}

func (m *CreateDatasetRequest) Reset()                    { *m = CreateDatasetRequest{} }
func (m *CreateDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDatasetRequest) ProtoMessage()               {}
func (*CreateDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateDatasetRequest) GetMeta() *vo.DatasetMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type UpdateDatasetRequest struct {
	ProjectId string                   `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DatasetId string                   `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	Meta      *vo.DatasetMetadataDelta `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
}

func (m *UpdateDatasetRequest) Reset()                    { *m = UpdateDatasetRequest{} }
func (m *UpdateDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDatasetRequest) ProtoMessage()               {}
func (*UpdateDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateDatasetRequest) GetMeta() *vo.DatasetMetadataDelta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ListProjectsRequest struct {
}

func (m *ListProjectsRequest) Reset()                    { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()               {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ListProjectsResponse struct {
	Projects []*ProjectInfo `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty"`
	Error    *ApiError      `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *ListProjectsResponse) Reset()                    { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()               {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListProjectsResponse) GetProjects() []*ProjectInfo {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *ListProjectsResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListDatasetsRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *ListDatasetsRequest) Reset()                    { *m = ListDatasetsRequest{} }
func (m *ListDatasetsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDatasetsRequest) ProtoMessage()               {}
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ListDatasetsResponse struct {
	Datasets []*DatasetInfo `protobuf:"bytes,1,rep,name=datasets" json:"datasets,omitempty"`
	Error    *ApiError      `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *ListDatasetsResponse) Reset()                    { *m = ListDatasetsResponse{} }
func (m *ListDatasetsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDatasetsResponse) ProtoMessage()               {}
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ListDatasetsResponse) GetDatasets() []*DatasetInfo {
	if m != nil {
		return m.Datasets
	}
	return nil
}

func (m *ListDatasetsResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type DatasetInfo struct {
	ProjectId       string     `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DatasetId       string     `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	UpdateTimestamp int64      `protobuf:"varint,3,opt,name=update_timestamp,json=updateTimestamp" json:"update_timestamp,omitempty"`
	Sample          *vo.Sample `protobuf:"bytes,4,opt,name=sample" json:"sample,omitempty"`
	Description     string     `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Summary         string     `protobuf:"bytes,7,opt,name=summary" json:"summary,omitempty"`
}

func (m *DatasetInfo) Reset()                    { *m = DatasetInfo{} }
func (m *DatasetInfo) String() string            { return proto.CompactTextString(m) }
func (*DatasetInfo) ProtoMessage()               {}
func (*DatasetInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DatasetInfo) GetSample() *vo.Sample {
	if m != nil {
		return m.Sample
	}
	return nil
}

type DatasetInfoResponse struct {
	ProjectId       string     `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DatasetId       string     `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	UpdateTimestamp int64      `protobuf:"varint,3,opt,name=update_timestamp,json=updateTimestamp" json:"update_timestamp,omitempty"`
	Sample          *vo.Sample `protobuf:"bytes,4,opt,name=sample" json:"sample,omitempty"`
	Description     string     `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Summary         string     `protobuf:"bytes,7,opt,name=summary" json:"summary,omitempty"`
	Error           *ApiError  `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *DatasetInfoResponse) Reset()                    { *m = DatasetInfoResponse{} }
func (m *DatasetInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*DatasetInfoResponse) ProtoMessage()               {}
func (*DatasetInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DatasetInfoResponse) GetSample() *vo.Sample {
	if m != nil {
		return m.Sample
	}
	return nil
}

func (m *DatasetInfoResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type StatRequest struct {
}

func (m *StatRequest) Reset()                    { *m = StatRequest{} }
func (m *StatRequest) String() string            { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()               {}
func (*StatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type StatResponse struct {
	Version    string    `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	EventCount uint64    `protobuf:"varint,2,opt,name=event_count,json=eventCount" json:"event_count,omitempty"`
	Error      *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *StatResponse) Reset()                    { *m = StatResponse{} }
func (m *StatResponse) String() string            { return proto.CompactTextString(m) }
func (*StatResponse) ProtoMessage()               {}
func (*StatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *StatResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

type ResetRequest struct {
}

func (m *ResetRequest) Reset()                    { *m = ResetRequest{} }
func (m *ResetRequest) String() string            { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()               {}
func (*ResetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type ApiError struct {
	Code    StatusCode `protobuf:"varint,1,opt,name=code,enum=StatusCode" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// e.g. duplicate_dataset
	DetailCode string `protobuf:"bytes,3,opt,name=detail_code,json=detailCode" json:"detail_code,omitempty"`
	// e.g. (project,dataset)
	DetailArgs []string `protobuf:"bytes,4,rep,name=detail_args,json=detailArgs" json:"detail_args,omitempty"`
	Details    string   `protobuf:"bytes,6,opt,name=details" json:"details,omitempty"`
}

func (m *ApiError) Reset()                    { *m = ApiError{} }
func (m *ApiError) String() string            { return proto.CompactTextString(m) }
func (*ApiError) ProtoMessage()               {}
func (*ApiError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type EmptyResponse struct {
	Error *ApiError `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *EmptyResponse) Reset()                    { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()               {}
func (*EmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *EmptyResponse) GetError() *ApiError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateProjectRequest)(nil), "CreateProjectRequest")
	proto.RegisterType((*GetProjectRequest)(nil), "GetProjectRequest")
	proto.RegisterType((*ProjectInfo)(nil), "ProjectInfo")
	proto.RegisterType((*ProjectInfoResponse)(nil), "ProjectInfoResponse")
	proto.RegisterType((*GetDatasetRequest)(nil), "GetDatasetRequest")
	proto.RegisterType((*CreateDatasetRequest)(nil), "CreateDatasetRequest")
	proto.RegisterType((*UpdateDatasetRequest)(nil), "UpdateDatasetRequest")
	proto.RegisterType((*ListProjectsRequest)(nil), "ListProjectsRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "ListProjectsResponse")
	proto.RegisterType((*ListDatasetsRequest)(nil), "ListDatasetsRequest")
	proto.RegisterType((*ListDatasetsResponse)(nil), "ListDatasetsResponse")
	proto.RegisterType((*DatasetInfo)(nil), "DatasetInfo")
	proto.RegisterType((*DatasetInfoResponse)(nil), "DatasetInfoResponse")
	proto.RegisterType((*StatRequest)(nil), "StatRequest")
	proto.RegisterType((*StatResponse)(nil), "StatResponse")
	proto.RegisterType((*ResetRequest)(nil), "ResetRequest")
	proto.RegisterType((*ApiError)(nil), "ApiError")
	proto.RegisterType((*EmptyResponse)(nil), "EmptyResponse")
	proto.RegisterEnum("StatusCode", StatusCode_name, StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Catalog service

type CatalogClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectInfoResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectInfoResponse, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*DatasetInfoResponse, error)
	GetDataset(ctx context.Context, in *GetDatasetRequest, opts ...grpc.CallOption) (*DatasetInfoResponse, error)
	ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error)
	UpdateDataset(ctx context.Context, in *UpdateDatasetRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type catalogClient struct {
	cc *grpc.ClientConn
}

func NewCatalogClient(cc *grpc.ClientConn) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectInfoResponse, error) {
	out := new(ProjectInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/CreateProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectInfoResponse, error) {
	out := new(ProjectInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/GetProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	out := new(ListProjectsResponse)
	err := grpc.Invoke(ctx, "/Catalog/ListProjects", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*DatasetInfoResponse, error) {
	out := new(DatasetInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/CreateDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetDataset(ctx context.Context, in *GetDatasetRequest, opts ...grpc.CallOption) (*DatasetInfoResponse, error) {
	out := new(DatasetInfoResponse)
	err := grpc.Invoke(ctx, "/Catalog/GetDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error) {
	out := new(ListDatasetsResponse)
	err := grpc.Invoke(ctx, "/Catalog/ListDatasets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) UpdateDataset(ctx context.Context, in *UpdateDatasetRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/Catalog/UpdateDataset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	out := new(StatResponse)
	err := grpc.Invoke(ctx, "/Catalog/Stat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/Catalog/Reset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Catalog service

type CatalogServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*ProjectInfoResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*ProjectInfoResponse, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	CreateDataset(context.Context, *CreateDatasetRequest) (*DatasetInfoResponse, error)
	GetDataset(context.Context, *GetDatasetRequest) (*DatasetInfoResponse, error)
	ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error)
	UpdateDataset(context.Context, *UpdateDatasetRequest) (*EmptyResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	Reset(context.Context, *ResetRequest) (*EmptyResponse, error)
}

func RegisterCatalogServer(s *grpc.Server, srv CatalogServer) {
	s.RegisterService(&_Catalog_serviceDesc, srv)
}

func _Catalog_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/ListProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_CreateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/CreateDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateDataset(ctx, req.(*CreateDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/GetDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetDataset(ctx, req.(*GetDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/ListDatasets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListDatasets(ctx, req.(*ListDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_UpdateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).UpdateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/UpdateDataset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).UpdateDataset(ctx, req.(*UpdateDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Catalog/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Catalog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _Catalog_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _Catalog_GetProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _Catalog_ListProjects_Handler,
		},
		{
			MethodName: "CreateDataset",
			Handler:    _Catalog_CreateDataset_Handler,
		},
		{
			MethodName: "GetDataset",
			Handler:    _Catalog_GetDataset_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _Catalog_ListDatasets_Handler,
		},
		{
			MethodName: "UpdateDataset",
			Handler:    _Catalog_UpdateDataset_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Catalog_Stat_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Catalog_Reset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("mlp_api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 963 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x56, 0x4f, 0x6f, 0xeb, 0x44,
	0x10, 0x6f, 0x9a, 0xb4, 0x69, 0xc7, 0x49, 0xba, 0xdd, 0x26, 0x60, 0x45, 0x42, 0xad, 0x2c, 0x21,
	0x15, 0x84, 0x2c, 0x54, 0x40, 0xe2, 0x02, 0xd2, 0xd6, 0xde, 0xb6, 0x56, 0x9d, 0x75, 0x59, 0xdb,
	0xe5, 0x71, 0xb2, 0x4c, 0xbd, 0xaf, 0xca, 0x53, 0x53, 0x1b, 0xdb, 0xad, 0xf4, 0x4e, 0xdc, 0xf8,
	0x1e, 0x7c, 0x26, 0x3e, 0x09, 0x77, 0x0e, 0x68, 0xd7, 0x76, 0xe3, 0xbe, 0x17, 0x94, 0x22, 0x90,
	0x10, 0x37, 0xcf, 0x6f, 0xfe, 0xfd, 0x66, 0xc6, 0xbb, 0xb3, 0x30, 0x5c, 0xdc, 0x65, 0x51, 0x9c,
	0xcd, 0xcd, 0x2c, 0x4f, 0xcb, 0x74, 0xba, 0xf3, 0x98, 0x56, 0x5f, 0xc6, 0x57, 0x30, 0xb6, 0x72,
	0x11, 0x97, 0xe2, 0x2a, 0x4f, 0xdf, 0x88, 0x9b, 0x92, 0x8b, 0x9f, 0x1e, 0x44, 0x51, 0xe2, 0x8f,
	0x00, 0xb2, 0x0a, 0x89, 0xe6, 0x89, 0xde, 0x39, 0xea, 0x1c, 0xef, 0xf2, 0xdd, 0x1a, 0x71, 0x12,
	0xe3, 0x04, 0xf6, 0xcf, 0x45, 0xf9, 0xf7, 0x7c, 0x3e, 0x03, 0xad, 0x76, 0x70, 0xee, 0x5f, 0xa7,
	0xeb, 0xac, 0x43, 0x38, 0x68, 0x59, 0x73, 0x51, 0x64, 0xe9, 0x7d, 0x21, 0xd6, 0x78, 0xe1, 0x43,
	0xd8, 0x12, 0x79, 0x9e, 0xe6, 0x7a, 0x72, 0xd4, 0x39, 0xd6, 0x4e, 0x76, 0x4d, 0x92, 0xcd, 0xa9,
	0x04, 0x78, 0x85, 0x1b, 0xdf, 0x29, 0xe2, 0x76, 0x5c, 0xc6, 0x85, 0x78, 0x21, 0x71, 0xa9, 0x4e,
	0x2a, 0x07, 0xa9, 0xde, 0xac, 0xd4, 0x35, 0xe2, 0x24, 0xc6, 0xcf, 0x4d, 0x0b, 0xff, 0xcd, 0xa8,
	0xf8, 0x13, 0xe8, 0x2d, 0x44, 0x19, 0xeb, 0x5d, 0x55, 0xc8, 0xc4, 0xac, 0x83, 0xcf, 0x44, 0x19,
	0x4b, 0x23, 0x5b, 0xdc, 0x95, 0x31, 0x57, 0x26, 0x92, 0x40, 0x98, 0x25, 0xff, 0x21, 0x81, 0x09,
	0x1c, 0xb8, 0xf3, 0xa2, 0xf9, 0x1d, 0x8a, 0x3a, 0xbf, 0x11, 0xc3, 0xf8, 0x39, 0x5c, 0xcf, 0xf0,
	0x18, 0x76, 0x6a, 0x16, 0x85, 0xde, 0x39, 0xea, 0x1e, 0x6b, 0x27, 0x03, 0xb3, 0x3d, 0xeb, 0x27,
	0xed, 0xfa, 0x71, 0x7e, 0x59, 0x65, 0xae, 0xb9, 0x15, 0x2f, 0xfc, 0x13, 0x6b, 0x62, 0x4b, 0xaf,
	0x25, 0xb1, 0xba, 0xfe, 0x25, 0xb1, 0xda, 0xa8, 0x22, 0xd6, 0x68, 0xd7, 0x13, 0xfb, 0xad, 0x03,
	0x5a, 0xcb, 0xf5, 0x1f, 0xcf, 0x02, 0x3d, 0xa8, 0x09, 0x47, 0xe5, 0x7c, 0x21, 0x8a, 0x32, 0x5e,
	0x64, 0x6a, 0x2e, 0x5d, 0xbe, 0x57, 0xe1, 0x41, 0x03, 0xe3, 0x43, 0xd8, 0x2e, 0xe2, 0x45, 0x76,
	0x27, 0xf4, 0x9e, 0xa2, 0xd6, 0x37, 0x7d, 0x25, 0xf2, 0x1a, 0xc6, 0x47, 0xa0, 0x25, 0xa2, 0xb8,
	0xc9, 0xe7, 0x59, 0x39, 0x4f, 0xef, 0xf5, 0x6d, 0x95, 0xab, 0x0d, 0x61, 0x1d, 0xfa, 0xc5, 0xc3,
	0x62, 0x11, 0xe7, 0x6f, 0xf5, 0xbe, 0xd2, 0x36, 0xa2, 0xf1, 0x47, 0x07, 0x0e, 0xda, 0x0d, 0x79,
	0xe1, 0xa9, 0xfc, 0x7f, 0x54, 0xb7, 0x7e, 0xa8, 0x43, 0xd0, 0xfc, 0x32, 0x6e, 0xce, 0x97, 0xf1,
	0x06, 0x06, 0x95, 0x58, 0x77, 0x41, 0x87, 0xfe, 0xa3, 0xc8, 0x0b, 0x99, 0xb7, 0x6a, 0x41, 0x23,
	0xe2, 0x43, 0xd0, 0xc4, 0xa3, 0xb8, 0x2f, 0xa3, 0x9b, 0xf4, 0xe1, 0xbe, 0x54, 0x1d, 0xe8, 0x71,
	0x50, 0x90, 0x25, 0x91, 0xf5, 0xa9, 0x47, 0x30, 0xe0, 0x62, 0x79, 0xb6, 0x8d, 0x5f, 0x3b, 0xb0,
	0xd3, 0xd8, 0xe0, 0x43, 0xe8, 0xdd, 0xa4, 0x89, 0x50, 0x59, 0x47, 0x27, 0x9a, 0x29, 0x59, 0x3d,
	0x14, 0x56, 0x9a, 0x08, 0xae, 0x14, 0x92, 0xd9, 0x42, 0x14, 0x45, 0x7c, 0x2b, 0xea, 0xee, 0x37,
	0xa2, 0x64, 0x96, 0x88, 0x32, 0x9e, 0xdf, 0x45, 0x2a, 0x42, 0x57, 0x69, 0xa1, 0x82, 0x64, 0x80,
	0x96, 0x41, 0x9c, 0xdf, 0x16, 0x7a, 0xef, 0xa8, 0xbb, 0x34, 0x20, 0xf9, 0x6d, 0x21, 0x63, 0x57,
	0x52, 0x51, 0x77, 0xbb, 0x11, 0x8d, 0xcf, 0x61, 0x48, 0x17, 0x59, 0xf9, 0xf6, 0xa9, 0x41, 0xeb,
	0xaa, 0xfc, 0xf4, 0xf7, 0x4d, 0x80, 0x25, 0x79, 0xbc, 0x0d, 0x9b, 0xde, 0x25, 0xda, 0xc0, 0x43,
	0xd8, 0xb5, 0x08, 0xb3, 0xa8, 0xeb, 0x52, 0x1b, 0x75, 0xb0, 0x06, 0xfd, 0x90, 0x5d, 0x32, 0xef,
	0x7b, 0x86, 0x36, 0xf1, 0x18, 0x90, 0xc3, 0xae, 0x89, 0xeb, 0xd8, 0x11, 0xe1, 0xe7, 0xe1, 0x8c,
	0xb2, 0x00, 0x75, 0xf1, 0x04, 0xf6, 0x6d, 0x4a, 0x6c, 0xd7, 0x61, 0x34, 0xa2, 0xaf, 0x2c, 0x4a,
	0x6d, 0x6a, 0xa3, 0x9e, 0x0c, 0xc4, 0xbc, 0x20, 0x3a, 0xf3, 0x42, 0x66, 0xa3, 0x2d, 0x8c, 0x61,
	0x44, 0x5c, 0x4e, 0x89, 0xfd, 0x43, 0x44, 0x5f, 0x39, 0x7e, 0xe0, 0xa3, 0x6d, 0xe9, 0x79, 0x45,
	0xf9, 0xcc, 0xf1, 0x7d, 0xc7, 0x63, 0x91, 0x4d, 0x99, 0x43, 0x6d, 0xd4, 0xc7, 0x07, 0xb0, 0x17,
	0x32, 0x12, 0x06, 0x17, 0x94, 0x05, 0x8e, 0x45, 0x02, 0x6a, 0x23, 0x84, 0x3f, 0x00, 0xcc, 0xa9,
	0xef, 0x85, 0xdc, 0x92, 0x59, 0x2e, 0x48, 0xe8, 0x4b, 0x7c, 0x07, 0x7f, 0x08, 0x07, 0x67, 0xc4,
	0x71, 0xa9, 0x1d, 0x5d, 0x71, 0x6a, 0x79, 0xcc, 0x76, 0x02, 0xc7, 0x63, 0x68, 0x57, 0x32, 0x27,
	0xa7, 0x1e, 0x97, 0x56, 0x80, 0x11, 0x0c, 0xbc, 0x30, 0x88, 0xbc, 0xb3, 0x88, 0x13, 0x76, 0x4e,
	0x91, 0x86, 0xf7, 0x61, 0x18, 0x32, 0x67, 0x76, 0xe5, 0x52, 0x59, 0x06, 0xb5, 0xd1, 0x00, 0x0f,
	0x60, 0xc7, 0x61, 0x01, 0xe5, 0x8c, 0xb8, 0x68, 0x88, 0xf7, 0x40, 0x0b, 0x19, 0xb9, 0x26, 0x8e,
	0x4b, 0x4e, 0x5d, 0x8a, 0x46, 0xb2, 0x20, 0x9b, 0x04, 0x24, 0x72, 0x3d, 0xdf, 0x47, 0x7b, 0xd2,
	0xfa, 0x94, 0xd8, 0x11, 0x23, 0x33, 0x8a, 0x12, 0x3c, 0x02, 0x90, 0x5f, 0x51, 0x40, 0x2e, 0x29,
	0x43, 0x42, 0xb6, 0xea, 0x9a, 0x72, 0x55, 0xd7, 0xcc, 0xf1, 0x67, 0x24, 0xb0, 0x2e, 0xd0, 0xeb,
	0x93, 0x5f, 0x7a, 0xd0, 0xb7, 0xe2, 0x32, 0xbe, 0x4b, 0x6f, 0xf1, 0xb7, 0x30, 0x7c, 0xf6, 0x1a,
	0xc0, 0x13, 0x73, 0xd5, 0xeb, 0x60, 0x3a, 0x36, 0x57, 0xec, 0x66, 0x63, 0x03, 0x7f, 0x0d, 0xb0,
	0x7c, 0x16, 0x60, 0x6c, 0xbe, 0xf7, 0x46, 0xf8, 0x4b, 0xcf, 0x6f, 0x60, 0xd0, 0xde, 0x15, 0x78,
	0x6c, 0xae, 0xd8, 0x28, 0xd3, 0x89, 0xb9, 0x6a, 0xa1, 0x18, 0x1b, 0x4b, 0xe2, 0xf5, 0xed, 0xf4,
	0x44, 0xfc, 0xf9, 0x4a, 0x9c, 0x8e, 0xcd, 0x15, 0xd7, 0xd7, 0x13, 0xf1, 0xc6, 0x59, 0x11, 0x7f,
	0xa1, 0x67, 0x4d, 0xbc, 0xd9, 0x25, 0x35, 0xf1, 0x77, 0x16, 0x52, 0x4d, 0xfc, 0xdd, 0x85, 0xa3,
	0x12, 0x0f, 0x9f, 0xed, 0x6e, 0x3c, 0x31, 0x57, 0xed, 0xf2, 0xe9, 0xc8, 0x7c, 0x76, 0x94, 0x8c,
	0x0d, 0xfc, 0x31, 0xf4, 0xe4, 0x51, 0xc1, 0x03, 0xb3, 0x75, 0x27, 0x4d, 0x87, 0x66, 0xfb, 0x4a,
	0x32, 0x36, 0xf0, 0x31, 0x6c, 0xa9, 0x8b, 0x03, 0x0f, 0xcd, 0xf6, 0x05, 0xf2, 0x7e, 0xc0, 0x1f,
	0xb7, 0xd5, 0x8b, 0xf0, 0x8b, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x33, 0x83, 0x86, 0x2b, 0x2c,
	0x0a, 0x00, 0x00,
}
