#!/bin/bash
set -euo pipefail

cd server
echo "Launching server..."
go run main.go -test --grpc localhost:9111 --web localhost:8080 &
cd ../specs --grpc localhost:9111 --web localhost:8080
venv/bin/python main.py
