#!/bin/bash
set -euo pipefail

make -C server clean build
echo "Launching server..."
server/dist/mlp-server --template-path=server --specs  --grpc localhost:9111 --web localhost:8080 &
cd specs 
venv/bin/python main.py --grpc localhost:9111 --web localhost:8080
