# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import events_pb2 as events__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x1a\x0c\x65vents.proto\">\n\x14\x43reateProjectRequest\x12\x11\n\tProjectId\x18\x01 \x01(\t\x12\x13\n\x0bProjectName\x18\x02 \x01(\t\"\x17\n\x15\x43reateProjectResponse\"&\n\x0c\x41pplyRequest\x12\x16\n\x06\x45vents\x18\x01 \x03(\x0b\x32\x06.Event\" \n\rApplyResponse\x12\x0f\n\x07Version\x18\x01 \x01(\x04\"7\n\rCreateDataset\x12\x12\n\ndataset_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\"\x14\n\x12\x44\x61tasetRequestMeta\"\x0c\n\nOkResponse\"J\n\x0fScenarioRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x16\n\x06\x45vents\x18\x02 \x03(\x0b\x32\x06.Event\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x18\n\x05\x45rror\x12\x0f\n\x07Message\x18\x01 \x01(\t\")\n\x10ScenarioResponse\x12\x15\n\x05\x45rror\x18\x01 \x01(\x0b\x32\x06.Error\"\r\n\x0bKillRequest\"\r\n\x0bPingRequest2u\n\x07\x43\x61talog\x12@\n\rCreateProject\x12\x15.CreateProjectRequest\x1a\x16.CreateProjectResponse\"\x00\x12(\n\x05\x41pply\x12\r.ApplyRequest\x1a\x0e.ApplyResponse\"\x00\x32z\n\x04Test\x12(\n\x05Setup\x12\x10.ScenarioRequest\x1a\x0b.OkResponse\"\x00\x12#\n\x04Kill\x12\x0c.KillRequest\x1a\x0b.OkResponse\"\x00\x12#\n\x04Ping\x12\x0c.PingRequest\x1a\x0b.OkResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[events__pb2.DESCRIPTOR,])




_CREATEPROJECTREQUEST = _descriptor.Descriptor(
  name='CreateProjectRequest',
  full_name='CreateProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ProjectId', full_name='CreateProjectRequest.ProjectId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ProjectName', full_name='CreateProjectRequest.ProjectName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=89,
)


_CREATEPROJECTRESPONSE = _descriptor.Descriptor(
  name='CreateProjectResponse',
  full_name='CreateProjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=114,
)


_APPLYREQUEST = _descriptor.Descriptor(
  name='ApplyRequest',
  full_name='ApplyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Events', full_name='ApplyRequest.Events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=154,
)


_APPLYRESPONSE = _descriptor.Descriptor(
  name='ApplyResponse',
  full_name='ApplyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Version', full_name='ApplyResponse.Version', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=188,
)


_CREATEDATASET = _descriptor.Descriptor(
  name='CreateDataset',
  full_name='CreateDataset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset_id', full_name='CreateDataset.dataset_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='CreateDataset.project_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=245,
)


_DATASETREQUESTMETA = _descriptor.Descriptor(
  name='DatasetRequestMeta',
  full_name='DatasetRequestMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=267,
)


_OKRESPONSE = _descriptor.Descriptor(
  name='OkResponse',
  full_name='OkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=281,
)


_SCENARIOREQUEST = _descriptor.Descriptor(
  name='ScenarioRequest',
  full_name='ScenarioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='ScenarioRequest.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Events', full_name='ScenarioRequest.Events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ScenarioRequest.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=357,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Message', full_name='Error.Message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=383,
)


_SCENARIORESPONSE = _descriptor.Descriptor(
  name='ScenarioResponse',
  full_name='ScenarioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Error', full_name='ScenarioResponse.Error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=426,
)


_KILLREQUEST = _descriptor.Descriptor(
  name='KillRequest',
  full_name='KillRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=441,
)


_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=456,
)

_APPLYREQUEST.fields_by_name['Events'].message_type = events__pb2._EVENT
_SCENARIOREQUEST.fields_by_name['Events'].message_type = events__pb2._EVENT
_SCENARIORESPONSE.fields_by_name['Error'].message_type = _ERROR
DESCRIPTOR.message_types_by_name['CreateProjectRequest'] = _CREATEPROJECTREQUEST
DESCRIPTOR.message_types_by_name['CreateProjectResponse'] = _CREATEPROJECTRESPONSE
DESCRIPTOR.message_types_by_name['ApplyRequest'] = _APPLYREQUEST
DESCRIPTOR.message_types_by_name['ApplyResponse'] = _APPLYRESPONSE
DESCRIPTOR.message_types_by_name['CreateDataset'] = _CREATEDATASET
DESCRIPTOR.message_types_by_name['DatasetRequestMeta'] = _DATASETREQUESTMETA
DESCRIPTOR.message_types_by_name['OkResponse'] = _OKRESPONSE
DESCRIPTOR.message_types_by_name['ScenarioRequest'] = _SCENARIOREQUEST
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['ScenarioResponse'] = _SCENARIORESPONSE
DESCRIPTOR.message_types_by_name['KillRequest'] = _KILLREQUEST
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateProjectRequest = _reflection.GeneratedProtocolMessageType('CreateProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPROJECTREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:CreateProjectRequest)
  })
_sym_db.RegisterMessage(CreateProjectRequest)

CreateProjectResponse = _reflection.GeneratedProtocolMessageType('CreateProjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPROJECTRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:CreateProjectResponse)
  })
_sym_db.RegisterMessage(CreateProjectResponse)

ApplyRequest = _reflection.GeneratedProtocolMessageType('ApplyRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPLYREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:ApplyRequest)
  })
_sym_db.RegisterMessage(ApplyRequest)

ApplyResponse = _reflection.GeneratedProtocolMessageType('ApplyResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPLYRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:ApplyResponse)
  })
_sym_db.RegisterMessage(ApplyResponse)

CreateDataset = _reflection.GeneratedProtocolMessageType('CreateDataset', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATASET,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:CreateDataset)
  })
_sym_db.RegisterMessage(CreateDataset)

DatasetRequestMeta = _reflection.GeneratedProtocolMessageType('DatasetRequestMeta', (_message.Message,), {
  'DESCRIPTOR' : _DATASETREQUESTMETA,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:DatasetRequestMeta)
  })
_sym_db.RegisterMessage(DatasetRequestMeta)

OkResponse = _reflection.GeneratedProtocolMessageType('OkResponse', (_message.Message,), {
  'DESCRIPTOR' : _OKRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:OkResponse)
  })
_sym_db.RegisterMessage(OkResponse)

ScenarioRequest = _reflection.GeneratedProtocolMessageType('ScenarioRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIOREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:ScenarioRequest)
  })
_sym_db.RegisterMessage(ScenarioRequest)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:Error)
  })
_sym_db.RegisterMessage(Error)

ScenarioResponse = _reflection.GeneratedProtocolMessageType('ScenarioResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIORESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:ScenarioResponse)
  })
_sym_db.RegisterMessage(ScenarioResponse)

KillRequest = _reflection.GeneratedProtocolMessageType('KillRequest', (_message.Message,), {
  'DESCRIPTOR' : _KILLREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:KillRequest)
  })
_sym_db.RegisterMessage(KillRequest)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)



_CATALOG = _descriptor.ServiceDescriptor(
  name='Catalog',
  full_name='Catalog',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=458,
  serialized_end=575,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateProject',
    full_name='Catalog.CreateProject',
    index=0,
    containing_service=None,
    input_type=_CREATEPROJECTREQUEST,
    output_type=_CREATEPROJECTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Apply',
    full_name='Catalog.Apply',
    index=1,
    containing_service=None,
    input_type=_APPLYREQUEST,
    output_type=_APPLYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CATALOG)

DESCRIPTOR.services_by_name['Catalog'] = _CATALOG


_TEST = _descriptor.ServiceDescriptor(
  name='Test',
  full_name='Test',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=577,
  serialized_end=699,
  methods=[
  _descriptor.MethodDescriptor(
    name='Setup',
    full_name='Test.Setup',
    index=0,
    containing_service=None,
    input_type=_SCENARIOREQUEST,
    output_type=_OKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Kill',
    full_name='Test.Kill',
    index=1,
    containing_service=None,
    input_type=_KILLREQUEST,
    output_type=_OKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='Test.Ping',
    index=2,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_OKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST)

DESCRIPTOR.services_by_name['Test'] = _TEST

# @@protoc_insertion_point(module_scope)
