// Code generated by protoc-gen-go.
// source: db.proto
// DO NOT EDIT!

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	JobRunEvent
	SystemLink
	EntityRef
	ProjectData
	Expert
	DatasetData
	DatasetVersionData
	SystemData
	SystemVersionData
	DatasetItemData
	Job
	JobRunData
	JobRunOutput
	TenantStats
	AssetCache
	FieldSchema
	DatasetDescriptor
	AppVersionData
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import vo "mlp/catalog/vo"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Range int32

const (
	Range_Events              Range = 0
	Range_PROJECTS            Range = 1
	Range_DATASETS            Range = 2
	Range_JOBS                Range = 4
	Range_STATS               Range = 5
	Range_ASSET_CACHE         Range = 6
	Range_EXPERTS             Range = 7
	Range_DATASET_VERSIONS    Range = 8
	Range_DATASET_HEAD_ITEMS  Range = 9
	Range_SYSTEMS             Range = 13
	Range_SYSTEM_VERSIONS     Range = 14
	Range_SYSTEM_LINKS        Range = 30
	Range_DATASET_BINARY_TREE Range = 22
	Range_PROJECT_NAMES       Range = 10
	Range_JOB_RUNS            Range = 12
	Range_JOB_RUN_HISTORY     Range = 47
	// scoped to project
	Range_NAMES_SCOPED         Range = 11
	Range_IDX_PROJECT_DATASETS Range = 20
	Range_IDX_DATASET_VERSIONS Range = 21
	// service UID/int32
	Range_IDX_SYSTEM_VERSIONS Range = 23
	Range_IDX_PROJECT_SYSTEMS Range = 24
	Range_IDX_PROJECT_JOBS    Range = 25
	Range_IDX_JOB_RUNS        Range = 26
	Range_VERSION             Range = 255
)

var Range_name = map[int32]string{
	0:   "Events",
	1:   "PROJECTS",
	2:   "DATASETS",
	4:   "JOBS",
	5:   "STATS",
	6:   "ASSET_CACHE",
	7:   "EXPERTS",
	8:   "DATASET_VERSIONS",
	9:   "DATASET_HEAD_ITEMS",
	13:  "SYSTEMS",
	14:  "SYSTEM_VERSIONS",
	30:  "SYSTEM_LINKS",
	22:  "DATASET_BINARY_TREE",
	10:  "PROJECT_NAMES",
	12:  "JOB_RUNS",
	47:  "JOB_RUN_HISTORY",
	11:  "NAMES_SCOPED",
	20:  "IDX_PROJECT_DATASETS",
	21:  "IDX_DATASET_VERSIONS",
	23:  "IDX_SYSTEM_VERSIONS",
	24:  "IDX_PROJECT_SYSTEMS",
	25:  "IDX_PROJECT_JOBS",
	26:  "IDX_JOB_RUNS",
	255: "VERSION",
}
var Range_value = map[string]int32{
	"Events":               0,
	"PROJECTS":             1,
	"DATASETS":             2,
	"JOBS":                 4,
	"STATS":                5,
	"ASSET_CACHE":          6,
	"EXPERTS":              7,
	"DATASET_VERSIONS":     8,
	"DATASET_HEAD_ITEMS":   9,
	"SYSTEMS":              13,
	"SYSTEM_VERSIONS":      14,
	"SYSTEM_LINKS":         30,
	"DATASET_BINARY_TREE":  22,
	"PROJECT_NAMES":        10,
	"JOB_RUNS":             12,
	"JOB_RUN_HISTORY":      47,
	"NAMES_SCOPED":         11,
	"IDX_PROJECT_DATASETS": 20,
	"IDX_DATASET_VERSIONS": 21,
	"IDX_SYSTEM_VERSIONS":  23,
	"IDX_PROJECT_SYSTEMS":  24,
	"IDX_PROJECT_JOBS":     25,
	"IDX_JOB_RUNS":         26,
	"VERSION":              255,
}

func (x Range) String() string {
	return proto.EnumName(Range_name, int32(x))
}
func (Range) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type JobRunEvent_Type int32

const (
	JobRunEvent_None      JobRunEvent_Type = 0
	JobRunEvent_Started   JobRunEvent_Type = 1
	JobRunEvent_Failed    JobRunEvent_Type = 2
	JobRunEvent_Completed JobRunEvent_Type = 3
	JobRunEvent_Logged    JobRunEvent_Type = 4
)

var JobRunEvent_Type_name = map[int32]string{
	0: "None",
	1: "Started",
	2: "Failed",
	3: "Completed",
	4: "Logged",
}
var JobRunEvent_Type_value = map[string]int32{
	"None":      0,
	"Started":   1,
	"Failed":    2,
	"Completed": 3,
	"Logged":    4,
}

func (x JobRunEvent_Type) String() string {
	return proto.EnumName(JobRunEvent_Type_name, int32(x))
}
func (JobRunEvent_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type SystemLink_Type int32

const (
	SystemLink_None             SystemLink_Type = 0
	SystemLink_Input_SystemVer  SystemLink_Type = 1
	SystemLink_Input_JobRun     SystemLink_Type = 2
	SystemLink_Output_SystemVer SystemLink_Type = 3
	SystemLink_Output_JobRun    SystemLink_Type = 4
)

var SystemLink_Type_name = map[int32]string{
	0: "None",
	1: "Input_SystemVer",
	2: "Input_JobRun",
	3: "Output_SystemVer",
	4: "Output_JobRun",
}
var SystemLink_Type_value = map[string]int32{
	"None":             0,
	"Input_SystemVer":  1,
	"Input_JobRun":     2,
	"Output_SystemVer": 3,
	"Output_JobRun":    4,
}

func (x SystemLink_Type) String() string {
	return proto.EnumName(SystemLink_Type_name, int32(x))
}
func (SystemLink_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type JobRunOutput_Type int32

const (
	JobRunOutput_None       JobRunOutput_Type = 0
	JobRunOutput_DatasetVer JobRunOutput_Type = 1
	JobRunOutput_SystemVer  JobRunOutput_Type = 2
)

var JobRunOutput_Type_name = map[int32]string{
	0: "None",
	1: "DatasetVer",
	2: "SystemVer",
}
var JobRunOutput_Type_value = map[string]int32{
	"None":       0,
	"DatasetVer": 1,
	"SystemVer":  2,
}

func (x JobRunOutput_Type) String() string {
	return proto.EnumName(JobRunOutput_Type_name, int32(x))
}
func (JobRunOutput_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12, 0} }

type JobRunEvent struct {
	Type      JobRunEvent_Type `protobuf:"varint,1,opt,name=type,enum=JobRunEvent_Type" json:"type,omitempty"`
	Log       string           `protobuf:"bytes,2,opt,name=log" json:"log,omitempty"`
	Title     string           `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Timestamp int64            `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *JobRunEvent) Reset()                    { *m = JobRunEvent{} }
func (m *JobRunEvent) String() string            { return proto.CompactTextString(m) }
func (*JobRunEvent) ProtoMessage()               {}
func (*JobRunEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// serviceID | Entity Container  | Exact Reference
type SystemLink struct {
	InstanceUid  []byte          `protobuf:"bytes,1,opt,name=instance_uid,json=instanceUid,proto3" json:"instance_uid,omitempty"`
	ContainerUid []byte          `protobuf:"bytes,2,opt,name=container_uid,json=containerUid,proto3" json:"container_uid,omitempty"`
	Type         SystemLink_Type `protobuf:"varint,3,opt,name=type,enum=SystemLink_Type" json:"type,omitempty"`
}

func (m *SystemLink) Reset()                    { *m = SystemLink{} }
func (m *SystemLink) String() string            { return proto.CompactTextString(m) }
func (*SystemLink) ProtoMessage()               {}
func (*SystemLink) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EntityRef struct {
	Kind vo.ENTITY `protobuf:"varint,1,opt,name=kind,enum=ENTITY" json:"kind,omitempty"`
	Uid  []byte    `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (m *EntityRef) Reset()                    { *m = EntityRef{} }
func (m *EntityRef) String() string            { return proto.CompactTextString(m) }
func (*EntityRef) ProtoMessage()               {}
func (*EntityRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ProjectData struct {
	Title        string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Uid          []byte `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	DatasetCount int32  `protobuf:"varint,4,opt,name=dataset_count,json=datasetCount" json:"dataset_count,omitempty"`
	StorageBytes int64  `protobuf:"varint,5,opt,name=storage_bytes,json=storageBytes" json:"storage_bytes,omitempty"`
	JobCount     int32  `protobuf:"varint,6,opt,name=job_count,json=jobCount" json:"job_count,omitempty"`
	Description  string `protobuf:"bytes,7,opt,name=description" json:"description,omitempty"`
	SystemCount  int32  `protobuf:"varint,8,opt,name=system_count,json=systemCount" json:"system_count,omitempty"`
}

func (m *ProjectData) Reset()                    { *m = ProjectData{} }
func (m *ProjectData) String() string            { return proto.CompactTextString(m) }
func (*ProjectData) ProtoMessage()               {}
func (*ProjectData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Expert struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Uid      []byte `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	FullName string `protobuf:"bytes,3,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
}

func (m *Expert) Reset()                    { *m = Expert{} }
func (m *Expert) String() string            { return proto.CompactTextString(m) }
func (*Expert) ProtoMessage()               {}
func (*Expert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DatasetData struct {
	Uid             []byte            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name            string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Title           string            `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	ProjectUid      []byte            `protobuf:"bytes,4,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	RecordCount     int64             `protobuf:"varint,5,opt,name=record_count,json=recordCount" json:"record_count,omitempty"`
	FileCount       int64             `protobuf:"varint,6,opt,name=file_count,json=fileCount" json:"file_count,omitempty"`
	StorageBytes    int64             `protobuf:"varint,7,opt,name=storage_bytes,json=storageBytes" json:"storage_bytes,omitempty"`
	Sample          *vo.DatasetSample `protobuf:"bytes,8,opt,name=sample" json:"sample,omitempty"`
	UpdateTimestamp int64             `protobuf:"varint,9,opt,name=update_timestamp,json=updateTimestamp" json:"update_timestamp,omitempty"`
	DataFormat      string            `protobuf:"bytes,10,opt,name=data_format,json=dataFormat" json:"data_format,omitempty"`
	Description     string            `protobuf:"bytes,11,opt,name=description" json:"description,omitempty"`
	LocationId      string            `protobuf:"bytes,12,opt,name=location_id,json=locationId" json:"location_id,omitempty"`
	LocationUri     string            `protobuf:"bytes,13,opt,name=location_uri,json=locationUri" json:"location_uri,omitempty"`
	Experts         [][]byte          `protobuf:"bytes,14,rep,name=experts,proto3" json:"experts,omitempty"`
	ProjectName     string            `protobuf:"bytes,17,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	HeadVersion     []byte            `protobuf:"bytes,20,opt,name=head_version,json=headVersion,proto3" json:"head_version,omitempty"`
	VersionCount    int32             `protobuf:"varint,22,opt,name=version_count,json=versionCount" json:"version_count,omitempty"`
}

func (m *DatasetData) Reset()                    { *m = DatasetData{} }
func (m *DatasetData) String() string            { return proto.CompactTextString(m) }
func (*DatasetData) ProtoMessage()               {}
func (*DatasetData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DatasetData) GetSample() *vo.DatasetSample {
	if m != nil {
		return m.Sample
	}
	return nil
}

type DatasetVersionData struct {
	Uid       []byte `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ParentUid []byte `protobuf:"bytes,2,opt,name=parent_uid,json=parentUid,proto3" json:"parent_uid,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	// total
	RecordCount  int64                  `protobuf:"varint,4,opt,name=record_count,json=recordCount" json:"record_count,omitempty"`
	ItemCount    int64                  `protobuf:"varint,5,opt,name=item_count,json=itemCount" json:"item_count,omitempty"`
	StorageBytes int64                  `protobuf:"varint,6,opt,name=storage_bytes,json=storageBytes" json:"storage_bytes,omitempty"`
	Inputs       []*vo.DatasetVerInput  `protobuf:"bytes,7,rep,name=inputs" json:"inputs,omitempty"`
	Items        []*vo.DatasetItem      `protobuf:"bytes,8,rep,name=items" json:"items,omitempty"`
	DatasetUid   []byte                 `protobuf:"bytes,9,opt,name=dataset_uid,json=datasetUid,proto3" json:"dataset_uid,omitempty"`
	Outputs      []*vo.DatasetVerOutput `protobuf:"bytes,10,rep,name=outputs" json:"outputs,omitempty"`
	VersionNum   int32                  `protobuf:"varint,11,opt,name=version_num,json=versionNum" json:"version_num,omitempty"`
	Timestamp    int64                  `protobuf:"varint,12,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *DatasetVersionData) Reset()                    { *m = DatasetVersionData{} }
func (m *DatasetVersionData) String() string            { return proto.CompactTextString(m) }
func (*DatasetVersionData) ProtoMessage()               {}
func (*DatasetVersionData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DatasetVersionData) GetInputs() []*vo.DatasetVerInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *DatasetVersionData) GetItems() []*vo.DatasetItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *DatasetVersionData) GetOutputs() []*vo.DatasetVerOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type SystemData struct {
	Uid              []byte        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name             string        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Title            string        `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	ProjectUid       []byte        `protobuf:"bytes,4,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Description      string        `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	LocationId       string        `protobuf:"bytes,6,opt,name=location_id,json=locationId" json:"location_id,omitempty"`
	LocationUri      string        `protobuf:"bytes,7,opt,name=location_uri,json=locationUri" json:"location_uri,omitempty"`
	Experts          [][]byte      `protobuf:"bytes,14,rep,name=experts,proto3" json:"experts,omitempty"`
	ProjectName      string        `protobuf:"bytes,8,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	VersionNum       int32         `protobuf:"varint,9,opt,name=version_num,json=versionNum" json:"version_num,omitempty"`
	VersionUid       []byte        `protobuf:"bytes,10,opt,name=version_uid,json=versionUid,proto3" json:"version_uid,omitempty"`
	VersionTimestamp int64         `protobuf:"varint,11,opt,name=version_timestamp,json=versionTimestamp" json:"version_timestamp,omitempty"`
	Kind             vo.SystemKind `protobuf:"varint,12,opt,name=kind,enum=SystemKind" json:"kind,omitempty"`
}

func (m *SystemData) Reset()                    { *m = SystemData{} }
func (m *SystemData) String() string            { return proto.CompactTextString(m) }
func (*SystemData) ProtoMessage()               {}
func (*SystemData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type SystemVersionData struct {
	Uid        []byte                    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Title      string                    `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	VersionNum int32                     `protobuf:"varint,3,opt,name=version_num,json=versionNum" json:"version_num,omitempty"`
	SystemUid  []byte                    `protobuf:"bytes,4,opt,name=system_uid,json=systemUid,proto3" json:"system_uid,omitempty"`
	Timestamp  int64                     `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Inputs     []*vo.SystemVersionInput  `protobuf:"bytes,10,rep,name=inputs" json:"inputs,omitempty"`
	Outputs    []*vo.SystemVersionOutput `protobuf:"bytes,11,rep,name=outputs" json:"outputs,omitempty"`
}

func (m *SystemVersionData) Reset()                    { *m = SystemVersionData{} }
func (m *SystemVersionData) String() string            { return proto.CompactTextString(m) }
func (*SystemVersionData) ProtoMessage()               {}
func (*SystemVersionData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SystemVersionData) GetInputs() []*vo.SystemVersionInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *SystemVersionData) GetOutputs() []*vo.SystemVersionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type DatasetItemData struct {
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	StorageBytes int64  `protobuf:"varint,3,opt,name=storage_bytes,json=storageBytes" json:"storage_bytes,omitempty"`
	RecordsCount int64  `protobuf:"varint,4,opt,name=records_count,json=recordsCount" json:"records_count,omitempty"`
}

func (m *DatasetItemData) Reset()                    { *m = DatasetItemData{} }
func (m *DatasetItemData) String() string            { return proto.CompactTextString(m) }
func (*DatasetItemData) ProtoMessage()               {}
func (*DatasetItemData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type Job struct {
	Uid            []byte   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProjectUid     []byte   `protobuf:"bytes,2,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Name           string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Title          string   `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Experts        [][]byte `protobuf:"bytes,7,rep,name=experts,proto3" json:"experts,omitempty"`
	RunNum         int32    `protobuf:"varint,8,opt,name=run_num,json=runNum" json:"run_num,omitempty"`
	RunUid         []byte   `protobuf:"bytes,10,opt,name=run_uid,json=runUid,proto3" json:"run_uid,omitempty"`
	ProjectName    string   `protobuf:"bytes,9,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	LastSuccessUid []byte   `protobuf:"bytes,11,opt,name=last_success_uid,json=lastSuccessUid,proto3" json:"last_success_uid,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type JobRunData struct {
	Uid             []byte            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	JobUid          []byte            `protobuf:"bytes,2,opt,name=job_uid,json=jobUid,proto3" json:"job_uid,omitempty"`
	Title           string            `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Inputs          []*vo.JobRunInput `protobuf:"bytes,4,rep,name=inputs" json:"inputs,omitempty"`
	Outputs         []*JobRunOutput   `protobuf:"bytes,5,rep,name=outputs" json:"outputs,omitempty"`
	StartTimestamp  int64             `protobuf:"varint,6,opt,name=start_timestamp,json=startTimestamp" json:"start_timestamp,omitempty"`
	UpdateTimestamp int64             `protobuf:"varint,9,opt,name=update_timestamp,json=updateTimestamp" json:"update_timestamp,omitempty"`
	Status          vo.JOB_STATUS     `protobuf:"varint,7,opt,name=status,enum=JOB_STATUS" json:"status,omitempty"`
	RunNum          int32             `protobuf:"varint,8,opt,name=run_num,json=runNum" json:"run_num,omitempty"`
	EventCount      int32             `protobuf:"varint,10,opt,name=event_count,json=eventCount" json:"event_count,omitempty"`
}

func (m *JobRunData) Reset()                    { *m = JobRunData{} }
func (m *JobRunData) String() string            { return proto.CompactTextString(m) }
func (*JobRunData) ProtoMessage()               {}
func (*JobRunData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *JobRunData) GetInputs() []*vo.JobRunInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *JobRunData) GetOutputs() []*JobRunOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type JobRunOutput struct {
	// dataset
	Uid  []byte            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type JobRunOutput_Type `protobuf:"varint,2,opt,name=type,enum=JobRunOutput_Type" json:"type,omitempty"`
}

func (m *JobRunOutput) Reset()                    { *m = JobRunOutput{} }
func (m *JobRunOutput) String() string            { return proto.CompactTextString(m) }
func (*JobRunOutput) ProtoMessage()               {}
func (*JobRunOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type TenantStats struct {
	ProjectCount int32 `protobuf:"varint,1,opt,name=project_count,json=projectCount" json:"project_count,omitempty"`
	DatasetCount int32 `protobuf:"varint,2,opt,name=dataset_count,json=datasetCount" json:"dataset_count,omitempty"`
	JobCount     int32 `protobuf:"varint,3,opt,name=job_count,json=jobCount" json:"job_count,omitempty"`
	ReportCount  int32 `protobuf:"varint,4,opt,name=report_count,json=reportCount" json:"report_count,omitempty"`
	ExpertCount  int32 `protobuf:"varint,5,opt,name=expert_count,json=expertCount" json:"expert_count,omitempty"`
	ModelCount   int32 `protobuf:"varint,6,opt,name=model_count,json=modelCount" json:"model_count,omitempty"`
	SystemCount  int32 `protobuf:"varint,7,opt,name=system_count,json=systemCount" json:"system_count,omitempty"`
}

func (m *TenantStats) Reset()                    { *m = TenantStats{} }
func (m *TenantStats) String() string            { return proto.CompactTextString(m) }
func (*TenantStats) ProtoMessage()               {}
func (*TenantStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type AssetCache struct {
	Digest []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Body   []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *AssetCache) Reset()                    { *m = AssetCache{} }
func (m *AssetCache) String() string            { return proto.CompactTextString(m) }
func (*AssetCache) ProtoMessage()               {}
func (*AssetCache) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type FieldSchema struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *FieldSchema) Reset()                    { *m = FieldSchema{} }
func (m *FieldSchema) String() string            { return proto.CompactTextString(m) }
func (*FieldSchema) ProtoMessage()               {}
func (*FieldSchema) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type DatasetDescriptor struct {
	Type         string         `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	RecordCount  int64          `protobuf:"varint,2,opt,name=record_count,json=recordCount" json:"record_count,omitempty"`
	Schema       []*FieldSchema `protobuf:"bytes,3,rep,name=schema" json:"schema,omitempty"`
	SampleString string         `protobuf:"bytes,4,opt,name=sample_string,json=sampleString" json:"sample_string,omitempty"`
}

func (m *DatasetDescriptor) Reset()                    { *m = DatasetDescriptor{} }
func (m *DatasetDescriptor) String() string            { return proto.CompactTextString(m) }
func (*DatasetDescriptor) ProtoMessage()               {}
func (*DatasetDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *DatasetDescriptor) GetSchema() []*FieldSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

type AppVersionData struct {
	ProjectionVersion string `protobuf:"bytes,1,opt,name=ProjectionVersion" json:"ProjectionVersion,omitempty"`
}

func (m *AppVersionData) Reset()                    { *m = AppVersionData{} }
func (m *AppVersionData) String() string            { return proto.CompactTextString(m) }
func (*AppVersionData) ProtoMessage()               {}
func (*AppVersionData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func init() {
	proto.RegisterType((*JobRunEvent)(nil), "JobRunEvent")
	proto.RegisterType((*SystemLink)(nil), "SystemLink")
	proto.RegisterType((*EntityRef)(nil), "EntityRef")
	proto.RegisterType((*ProjectData)(nil), "ProjectData")
	proto.RegisterType((*Expert)(nil), "Expert")
	proto.RegisterType((*DatasetData)(nil), "DatasetData")
	proto.RegisterType((*DatasetVersionData)(nil), "DatasetVersionData")
	proto.RegisterType((*SystemData)(nil), "SystemData")
	proto.RegisterType((*SystemVersionData)(nil), "SystemVersionData")
	proto.RegisterType((*DatasetItemData)(nil), "DatasetItemData")
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*JobRunData)(nil), "JobRunData")
	proto.RegisterType((*JobRunOutput)(nil), "JobRunOutput")
	proto.RegisterType((*TenantStats)(nil), "TenantStats")
	proto.RegisterType((*AssetCache)(nil), "AssetCache")
	proto.RegisterType((*FieldSchema)(nil), "FieldSchema")
	proto.RegisterType((*DatasetDescriptor)(nil), "DatasetDescriptor")
	proto.RegisterType((*AppVersionData)(nil), "AppVersionData")
	proto.RegisterEnum("Range", Range_name, Range_value)
	proto.RegisterEnum("JobRunEvent_Type", JobRunEvent_Type_name, JobRunEvent_Type_value)
	proto.RegisterEnum("SystemLink_Type", SystemLink_Type_name, SystemLink_Type_value)
	proto.RegisterEnum("JobRunOutput_Type", JobRunOutput_Type_name, JobRunOutput_Type_value)
}

func init() { proto.RegisterFile("db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x58, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x0e, 0x45, 0x9d, 0x38, 0xa4, 0xe5, 0xd5, 0xc6, 0xbf, 0xcd, 0x3f, 0x69, 0x6a, 0x47, 0x49,
	0x13, 0xb7, 0x29, 0x14, 0x20, 0x45, 0x81, 0xa2, 0x17, 0x05, 0x64, 0x8b, 0x41, 0xe4, 0x24, 0xb2,
	0x41, 0xca, 0x41, 0x7c, 0xc5, 0x52, 0xe2, 0xda, 0xa1, 0x23, 0x91, 0x02, 0xb9, 0x0a, 0xea, 0x07,
	0xe9, 0x5d, 0xfb, 0x0e, 0x7d, 0x84, 0xf6, 0x09, 0xfa, 0x02, 0x7d, 0x8d, 0xf6, 0xa6, 0x40, 0x5b,
	0xec, 0x81, 0x22, 0x29, 0xca, 0x0d, 0x8a, 0xa2, 0x77, 0xe4, 0x37, 0xa3, 0xe1, 0xce, 0xcc, 0x37,
	0x87, 0x15, 0x34, 0xfd, 0x71, 0x77, 0x1e, 0x47, 0x34, 0xba, 0xd5, 0x7c, 0x17, 0x89, 0xa7, 0xce,
	0x8f, 0x0a, 0xe8, 0x47, 0xd1, 0xd8, 0x5e, 0x84, 0xd6, 0x3b, 0x12, 0x52, 0xfc, 0x11, 0x54, 0xe9,
	0xd5, 0x9c, 0x98, 0xca, 0x9e, 0xb2, 0xdf, 0x7a, 0xd2, 0xee, 0xe6, 0x64, 0xdd, 0xd1, 0xd5, 0x9c,
	0xd8, 0x5c, 0x8c, 0x11, 0xa8, 0xd3, 0xe8, 0xc2, 0xac, 0xec, 0x29, 0xfb, 0x9a, 0xcd, 0x1e, 0xf1,
	0x16, 0xd4, 0x68, 0x40, 0xa7, 0xc4, 0x54, 0x39, 0x26, 0x5e, 0xf0, 0x07, 0xa0, 0xd1, 0x60, 0x46,
	0x12, 0xea, 0xcd, 0xe6, 0x66, 0x75, 0x4f, 0xd9, 0x57, 0xed, 0x0c, 0xe8, 0xf4, 0xa1, 0xca, 0x6c,
	0xe2, 0x26, 0x54, 0x87, 0x51, 0x48, 0xd0, 0x0d, 0xac, 0x43, 0xc3, 0xa1, 0x5e, 0x4c, 0x89, 0x8f,
	0x14, 0x0c, 0x50, 0x7f, 0xea, 0x05, 0x53, 0xe2, 0xa3, 0x0a, 0xde, 0x00, 0xed, 0x30, 0x9a, 0xcd,
	0xa7, 0x84, 0x89, 0x54, 0x26, 0x7a, 0x11, 0x5d, 0x5c, 0x10, 0x1f, 0x55, 0x3b, 0xbf, 0x28, 0x00,
	0xce, 0x55, 0x42, 0xc9, 0xec, 0x45, 0x10, 0xbe, 0xc5, 0x77, 0xc1, 0x08, 0xc2, 0x84, 0x7a, 0xe1,
	0x84, 0xb8, 0x8b, 0xc0, 0xe7, 0x9e, 0x18, 0xb6, 0x9e, 0x62, 0xa7, 0x81, 0x8f, 0xef, 0xc1, 0xc6,
	0x24, 0x0a, 0xa9, 0x17, 0x84, 0x24, 0xe6, 0x3a, 0x15, 0xae, 0x63, 0x2c, 0x41, 0xa6, 0x74, 0x5f,
	0x46, 0x42, 0xe5, 0x91, 0x40, 0xdd, 0xec, 0x13, 0xb9, 0x40, 0x74, 0xbe, 0x2e, 0xb9, 0x70, 0x13,
	0x36, 0x07, 0xe1, 0x7c, 0x41, 0x5d, 0xf1, 0x83, 0x57, 0x24, 0x46, 0x0a, 0x46, 0x60, 0x08, 0x50,
	0xc4, 0x13, 0x55, 0xf0, 0x16, 0xa0, 0xe3, 0x05, 0x2d, 0xea, 0xa9, 0xb8, 0x0d, 0x1b, 0x12, 0x95,
	0x8a, 0xd5, 0xce, 0x97, 0xa0, 0x59, 0x21, 0x0d, 0xe8, 0x95, 0x4d, 0xce, 0xf1, 0x6d, 0xa8, 0xbe,
	0x0d, 0x42, 0x5f, 0xa6, 0xa7, 0xd1, 0xb5, 0x86, 0xa3, 0xc1, 0xe8, 0xcc, 0xe6, 0x20, 0x4b, 0x4a,
	0xe6, 0x0c, 0x7b, 0xec, 0xfc, 0xaa, 0x80, 0x7e, 0x12, 0x47, 0x97, 0x64, 0x42, 0xfb, 0x1e, 0xf5,
	0xb2, 0x24, 0x29, 0xf9, 0x24, 0x61, 0xa8, 0x86, 0xde, 0x8c, 0xc8, 0x6c, 0xf2, 0xe7, 0xd4, 0x96,
	0xba, 0xb4, 0xc5, 0x82, 0xe6, 0x7b, 0xd4, 0x4b, 0x08, 0x75, 0x27, 0xd1, 0x22, 0xa4, 0x3c, 0x9d,
	0x35, 0xdb, 0x90, 0xe0, 0x21, 0xc3, 0x98, 0x52, 0x42, 0xa3, 0xd8, 0xbb, 0x20, 0xee, 0xf8, 0x8a,
	0x92, 0xc4, 0xac, 0xf1, 0x9c, 0x1b, 0x12, 0x3c, 0x60, 0x18, 0xbe, 0x0d, 0xda, 0x65, 0x34, 0x96,
	0x56, 0xea, 0xdc, 0x4a, 0xf3, 0x32, 0x1a, 0x0b, 0x0b, 0x7b, 0xa0, 0xfb, 0x24, 0x99, 0xc4, 0xc1,
	0x9c, 0x06, 0x51, 0x68, 0x36, 0xf8, 0x99, 0xf2, 0x10, 0x4b, 0x70, 0xc2, 0x43, 0x26, 0x2d, 0x34,
	0xb9, 0x05, 0x5d, 0x60, 0xdc, 0x48, 0xc7, 0x83, 0xba, 0xf5, 0xcd, 0x9c, 0xc4, 0x74, 0xe9, 0x9b,
	0x52, 0xf6, 0x2d, 0x8b, 0x13, 0x3b, 0xd1, 0xf9, 0x62, 0x3a, 0x75, 0xb9, 0xaa, 0x20, 0x70, 0x93,
	0x01, 0x43, 0xa6, 0xbe, 0x05, 0x35, 0x32, 0xf3, 0x82, 0x29, 0x77, 0x58, 0xb3, 0xc5, 0x4b, 0xe7,
	0x87, 0x2a, 0xe8, 0x7d, 0xe1, 0x3a, 0x0f, 0xad, 0x34, 0xaa, 0x64, 0x46, 0xd7, 0x85, 0x75, 0x7d,
	0x95, 0xec, 0x82, 0x3e, 0x17, 0x59, 0xe2, 0x6c, 0xac, 0x72, 0x1b, 0x20, 0x21, 0xc6, 0xc5, 0xbb,
	0x60, 0xc4, 0x64, 0x12, 0xc5, 0xbe, 0x74, 0x59, 0x44, 0x55, 0x17, 0x98, 0x88, 0xdb, 0x1d, 0x80,
	0xf3, 0x60, 0x4a, 0x72, 0x51, 0x55, 0x6d, 0x8d, 0x21, 0xd7, 0x24, 0xa6, 0xb1, 0x26, 0x31, 0x0f,
	0xa0, 0x9e, 0x78, 0xac, 0xc8, 0x78, 0x4c, 0xf5, 0x27, 0xad, 0xae, 0xf4, 0xd0, 0xe1, 0xa8, 0x2d,
	0xa5, 0xf8, 0x63, 0x40, 0x8b, 0xb9, 0xef, 0x51, 0xe2, 0x66, 0xc5, 0xad, 0x71, 0x7b, 0x9b, 0x02,
	0x1f, 0xa5, 0x30, 0x73, 0x8d, 0x11, 0xc4, 0x3d, 0x8f, 0xe2, 0x99, 0x47, 0x4d, 0xe0, 0x6e, 0x03,
	0x83, 0x9e, 0x72, 0x64, 0x35, 0xdf, 0x7a, 0x39, 0xdf, 0xbb, 0xa0, 0x4f, 0xa3, 0x89, 0xc7, 0x9e,
	0xdd, 0xc0, 0x37, 0x0d, 0x61, 0x22, 0x85, 0x06, 0x3c, 0x3a, 0x4b, 0x85, 0x45, 0x1c, 0x98, 0x1b,
	0xc2, 0x46, 0x8a, 0x9d, 0xc6, 0x01, 0x36, 0xa1, 0x41, 0x38, 0x21, 0x12, 0xb3, 0xb5, 0xa7, 0xee,
	0x1b, 0x76, 0xfa, 0xca, 0x7e, 0x9c, 0xc6, 0x9e, 0x67, 0xab, 0x2d, 0x7e, 0x2c, 0x31, 0x4e, 0x80,
	0xbb, 0x60, 0xbc, 0x21, 0x9e, 0xef, 0xbe, 0x23, 0x71, 0xc2, 0xce, 0xb8, 0x25, 0x3a, 0x0a, 0xc3,
	0x5e, 0x09, 0x88, 0x85, 0x57, 0x4a, 0x65, 0x02, 0xb6, 0x45, 0x71, 0x48, 0x50, 0xb0, 0xf2, 0x7b,
	0x15, 0xb0, 0x0c, 0xa8, 0xfc, 0xdd, 0x35, 0xcc, 0xb9, 0x03, 0x30, 0xf7, 0x62, 0x12, 0xd2, 0x5c,
	0x73, 0xd2, 0x04, 0xc2, 0xd8, 0xb0, 0x9e, 0x44, 0xab, 0x1c, 0xa9, 0xae, 0xe5, 0x48, 0x90, 0xd5,
	0x8d, 0x20, 0x91, 0x16, 0xa4, 0x55, 0x53, 0xe6, 0x48, 0x7d, 0x0d, 0x47, 0xf6, 0xa1, 0x1e, 0xb0,
	0x4e, 0xc6, 0x18, 0xa4, 0xee, 0xeb, 0x4f, 0x50, 0x37, 0x73, 0x89, 0xb7, 0x38, 0x5b, 0xca, 0x71,
	0x07, 0x6a, 0xcc, 0x76, 0x62, 0x36, 0xb9, 0xa2, 0x91, 0x2a, 0x0e, 0x28, 0x99, 0xd9, 0x42, 0x94,
	0xd2, 0x83, 0x35, 0x15, 0xe6, 0xaa, 0x26, 0x98, 0x2f, 0x21, 0xe6, 0xeb, 0x23, 0x68, 0x44, 0xbc,
	0x21, 0x26, 0x26, 0x70, 0x33, 0xed, 0xdc, 0xf7, 0x44, 0xab, 0xb4, 0x53, 0x0d, 0x66, 0x2d, 0xcd,
	0x42, 0xb8, 0x98, 0x71, 0x2e, 0xd5, 0x6c, 0x90, 0xd0, 0x70, 0x31, 0x2b, 0x8e, 0x23, 0x63, 0x75,
	0x1c, 0x7d, 0xa7, 0xa6, 0x83, 0xe4, 0xbf, 0xaf, 0xe8, 0x15, 0xda, 0xd7, 0xde, 0x4b, 0xfb, 0xfa,
	0x7b, 0x69, 0xdf, 0xf8, 0x37, 0xb4, 0x6f, 0x96, 0x69, 0xbf, 0x12, 0x4d, 0xad, 0x14, 0xcd, 0x9c,
	0x02, 0x73, 0x12, 0x84, 0x93, 0x12, 0x12, 0xc9, 0x6b, 0xa7, 0x0a, 0x59, 0xd8, 0x75, 0x1e, 0x76,
	0x24, 0x05, 0xf9, 0x4e, 0x21, 0x46, 0x9b, 0xc1, 0x47, 0x9b, 0x2e, 0xe7, 0xed, 0xf3, 0x20, 0xf4,
	0xc5, 0x78, 0xeb, 0xfc, 0xa6, 0x40, 0x7b, 0x39, 0x2b, 0xff, 0xa6, 0x7a, 0x96, 0x19, 0xa9, 0xac,
	0x64, 0x24, 0xef, 0x8d, 0x5a, 0xf2, 0xe6, 0x0e, 0x80, 0x1c, 0x2b, 0x59, 0xc6, 0x34, 0x81, 0x30,
	0x5f, 0x0a, 0xd4, 0xa9, 0xad, 0x50, 0x07, 0x3f, 0x5a, 0x56, 0x85, 0x60, 0xe9, 0xcd, 0x6e, 0xe1,
	0xa4, 0xc5, 0xc2, 0xe8, 0x66, 0x9c, 0xd6, 0xb9, 0xf6, 0x56, 0x51, 0x7b, 0x85, 0xd6, 0x9d, 0x08,
	0x36, 0x73, 0xa5, 0xc3, 0xbd, 0x5e, 0xc7, 0xc4, 0x52, 0xf9, 0xaa, 0x6b, 0xca, 0xf7, 0x1e, 0x6c,
	0x88, 0x8e, 0x90, 0x14, 0xda, 0x84, 0x6c, 0x1d, 0x89, 0x68, 0x54, 0xbf, 0x2b, 0xa0, 0x1e, 0x45,
	0xe3, 0x35, 0xb1, 0x5d, 0xe1, 0x75, 0xa5, 0xc4, 0xeb, 0xf4, 0x60, 0xea, 0xba, 0x12, 0xa9, 0xe6,
	0x13, 0x92, 0xe3, 0x66, 0xa3, 0xc8, 0xcd, 0x1d, 0x68, 0xc4, 0x0b, 0x91, 0x26, 0x31, 0xdb, 0xeb,
	0xf1, 0x82, 0xa7, 0x48, 0x0a, 0x32, 0xb2, 0x31, 0x81, 0x9c, 0x8f, 0x05, 0x36, 0x6b, 0x65, 0x36,
	0xef, 0x03, 0x9a, 0x7a, 0x09, 0x75, 0x93, 0xc5, 0x64, 0x42, 0x92, 0x84, 0x1b, 0xd1, 0xb9, 0x91,
	0x16, 0xc3, 0x1d, 0x01, 0x9f, 0x06, 0x7e, 0xe7, 0xe7, 0x0a, 0x80, 0xd8, 0xbe, 0xae, 0x21, 0xd8,
	0x0e, 0x34, 0xd8, 0xfe, 0x92, 0x05, 0xa0, 0x7e, 0x19, 0x8d, 0xaf, 0x6f, 0xcc, 0xf7, 0x97, 0xdc,
	0xa8, 0xca, 0x46, 0x28, 0xac, 0x17, 0x49, 0xf1, 0x30, 0x23, 0x45, 0x8d, 0xab, 0x6d, 0x48, 0xb5,
	0xd5, 0x26, 0xf7, 0x10, 0x36, 0x13, 0xb6, 0x22, 0xe7, 0x4a, 0x4a, 0xf4, 0xe9, 0x16, 0x87, 0xb3,
	0x82, 0xfa, 0x07, 0x53, 0xfa, 0x1e, 0xd4, 0x13, 0xea, 0xd1, 0x85, 0x58, 0x0b, 0x58, 0xf5, 0x1d,
	0x1d, 0x1f, 0xb8, 0xce, 0xa8, 0x37, 0x3a, 0x75, 0x6c, 0x29, 0xba, 0x3e, 0x2d, 0xbb, 0xa0, 0x13,
	0x76, 0x41, 0x90, 0x8c, 0x02, 0x51, 0x5a, 0x1c, 0x12, 0x7c, 0xba, 0x02, 0x23, 0xef, 0xcb, 0x9a,
	0x90, 0x3e, 0x90, 0xcb, 0x76, 0x85, 0x7f, 0x1e, 0x17, 0x5c, 0xcf, 0xaf, 0xdb, 0x8f, 0x4b, 0xeb,
	0x76, 0x0b, 0x20, 0x1b, 0x08, 0x48, 0x61, 0x17, 0x85, 0x6c, 0xa1, 0xae, 0x74, 0xfe, 0x50, 0x40,
	0x1f, 0x91, 0xd0, 0x0b, 0xa9, 0x43, 0x3d, 0xca, 0xf9, 0x9f, 0x32, 0x45, 0x9c, 0x56, 0x11, 0x83,
	0x5a, 0x82, 0xcb, 0x41, 0x58, 0x5c, 0x75, 0x2b, 0x6b, 0x56, 0xdd, 0xc2, 0x16, 0xab, 0xae, 0x6c,
	0xb1, 0x7c, 0x18, 0xcf, 0xa3, 0xb8, 0xb8, 0x2b, 0xeb, 0x02, 0x5b, 0xaa, 0x08, 0xc2, 0xe7, 0xc6,
	0x71, 0xcd, 0xd6, 0x05, 0x26, 0x54, 0x76, 0x41, 0x9f, 0x45, 0x3e, 0x99, 0x16, 0x56, 0x65, 0xe0,
	0xd0, 0xd2, 0x46, 0x61, 0x15, 0x6e, 0x94, 0x57, 0xe1, 0x2f, 0x00, 0x7a, 0x09, 0x3b, 0xb4, 0x37,
	0x79, 0x43, 0xf0, 0x36, 0xd4, 0xfd, 0xe0, 0x82, 0x24, 0x54, 0x06, 0x5f, 0xbe, 0xb1, 0xb2, 0x1d,
	0x47, 0xfe, 0x95, 0xe4, 0x33, 0x7f, 0xee, 0x7c, 0x0e, 0xfa, 0xd3, 0x80, 0x4c, 0x7d, 0x67, 0xf2,
	0x86, 0xcc, 0xbc, 0xb5, 0x9b, 0x34, 0xce, 0xa5, 0x4d, 0x93, 0x29, 0xfa, 0x56, 0x81, 0x76, 0xba,
	0x18, 0xcb, 0x71, 0x16, 0xc5, 0x4b, 0x4d, 0x25, 0xd3, 0x2c, 0x6d, 0x2c, 0x95, 0xf2, 0xc6, 0x72,
	0x1f, 0xea, 0x09, 0xff, 0xbc, 0xa9, 0xca, 0xda, 0xc9, 0x1d, 0xc9, 0x96, 0x32, 0xde, 0xf9, 0xf8,
	0x66, 0xea, 0x26, 0x34, 0x0e, 0xc2, 0x0b, 0xd9, 0x68, 0x0c, 0x01, 0x3a, 0x1c, 0xeb, 0x7c, 0x05,
	0xad, 0xde, 0x7c, 0x9e, 0x1f, 0x1d, 0x9f, 0x42, 0x5b, 0x5e, 0x8e, 0x82, 0x28, 0x94, 0x02, 0x79,
	0xc0, 0xb2, 0xe0, 0x93, 0x9f, 0x54, 0xa8, 0xd9, 0x5e, 0x78, 0x41, 0xd8, 0xe5, 0x93, 0x5f, 0x88,
	0x13, 0x74, 0x03, 0x1b, 0xd0, 0x3c, 0xb1, 0x8f, 0x8f, 0xac, 0xc3, 0x91, 0x83, 0x14, 0xf6, 0xd6,
	0xef, 0x8d, 0x7a, 0x8e, 0x35, 0x72, 0x50, 0x85, 0x91, 0xf4, 0xe8, 0xf8, 0xc0, 0x41, 0x55, 0xac,
	0x41, 0x8d, 0x15, 0x93, 0x83, 0x6a, 0x78, 0x13, 0xf4, 0x9e, 0xe3, 0x58, 0x23, 0xf7, 0xb0, 0x77,
	0xf8, 0xcc, 0x42, 0x75, 0x76, 0xe5, 0xb5, 0x5e, 0x9f, 0x58, 0xf6, 0xc8, 0x41, 0x0d, 0x76, 0x2b,
	0x94, 0x06, 0xdc, 0x57, 0x96, 0xed, 0x0c, 0x8e, 0x87, 0x0e, 0x6a, 0xe2, 0x6d, 0xc0, 0x29, 0xfa,
	0xcc, 0xea, 0xf5, 0xdd, 0xc1, 0xc8, 0x7a, 0xe9, 0x20, 0x8d, 0xdf, 0x96, 0xcf, 0x1c, 0xfe, 0xb2,
	0xc1, 0xee, 0x9d, 0xe2, 0x25, 0xfb, 0x65, 0x8b, 0xdd, 0x3b, 0x25, 0xf8, 0x62, 0x30, 0x7c, 0xee,
	0xa0, 0x0f, 0xf1, 0x0e, 0xdc, 0x4c, 0x6d, 0x1d, 0x0c, 0x86, 0x3d, 0xfb, 0xcc, 0x1d, 0xd9, 0x96,
	0x85, 0xb6, 0xd9, 0xd5, 0x53, 0x7a, 0xe2, 0x0e, 0x7b, 0x2f, 0x2d, 0x07, 0x01, 0x73, 0x87, 0xf5,
	0x01, 0xfb, 0x74, 0xe8, 0x20, 0x83, 0x7d, 0x40, 0xbe, 0xb9, 0xcf, 0x06, 0xce, 0xe8, 0xd8, 0x3e,
	0x43, 0x8f, 0xd9, 0x07, 0xb8, 0xb6, 0xeb, 0x1c, 0x1e, 0x9f, 0x58, 0x7d, 0xa4, 0x63, 0x13, 0xb6,
	0x06, 0xfd, 0xd7, 0x6e, 0x6a, 0x6b, 0x19, 0x8f, 0xad, 0x54, 0x52, 0x72, 0xf0, 0x7f, 0xec, 0x50,
	0x4c, 0xb2, 0x7a, 0xfe, 0x9d, 0x54, 0x90, 0x1a, 0x4b, 0xbd, 0x35, 0x59, 0xa0, 0xf2, 0x02, 0x1e,
	0xe7, 0xff, 0xf3, 0x6b, 0x76, 0xff, 0xb5, 0xbb, 0x3c, 0xf4, 0x2d, 0x6c, 0x40, 0x43, 0x9a, 0x43,
	0x7f, 0x2a, 0xe3, 0x3a, 0xff, 0xd3, 0xe3, 0xb3, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x32, 0xd2,
	0x77, 0xb8, 0x0a, 0x11, 0x00, 0x00,
}
